// Code generated by javagen. DO NOT EDIT.

package p2p

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// WifiP2pManagerDeviceInfoListener wraps android.net.wifi.p2p.WifiP2pManager$DeviceInfoListener.
type WifiP2pManagerDeviceInfoListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnDeviceInfoAvailable calls android.net.wifi.p2p.WifiP2pManager$DeviceInfoListener.onDeviceInfoAvailable.
func (m *WifiP2pManagerDeviceInfoListener) OnDeviceInfoAvailable(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midWifiP2pManagerDeviceInfoListenerOnDeviceInfoAvailable == nil {
			callErr = fmt.Errorf("android.net.wifi.p2p.WifiP2pManager$DeviceInfoListener.onDeviceInfoAvailable is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midWifiP2pManagerDeviceInfoListenerOnDeviceInfoAvailable, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}
