// Code generated by javagen. DO NOT EDIT.

package vibrator

import "github.com/AndroidGoLab/jni/os/vibrator/consts"

const (
	VibrationEffectSupportNo      = consts.VibrationEffectSupportNo
	VibrationEffectSupportUnknown = consts.VibrationEffectSupportUnknown
	VibrationEffectSupportYes     = consts.VibrationEffectSupportYes
	Creator                       = consts.Creator
)
