// Code generated by javagen. DO NOT EDIT.

package wifi

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ManagerSuggestionConnectionStatusListener wraps android.net.wifi.WifiManager$SuggestionConnectionStatusListener.
type ManagerSuggestionConnectionStatusListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnConnectionStatus calls android.net.wifi.WifiManager$SuggestionConnectionStatusListener.onConnectionStatus.
func (m *ManagerSuggestionConnectionStatusListener) OnConnectionStatus(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midManagerSuggestionConnectionStatusListenerOnConnectionStatus == nil {
			callErr = fmt.Errorf("android.net.wifi.WifiManager$SuggestionConnectionStatusListener.onConnectionStatus is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midManagerSuggestionConnectionStatusListenerOnConnectionStatus, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.net.wifi.WifiManager$SuggestionConnectionStatusListener.toString.
func (m *ManagerSuggestionConnectionStatusListener) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midManagerSuggestionConnectionStatusListenerToString == nil {
			callErr = fmt.Errorf("android.net.wifi.WifiManager$SuggestionConnectionStatusListener.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midManagerSuggestionConnectionStatusListenerToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
