// Code generated by protogen. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/speech/speech.proto

package speech

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecognizerService_CreateRecognizer_FullMethodName       = "/speech.RecognizerService/CreateRecognizer"
	RecognizerService_IsRecognitionAvailable_FullMethodName = "/speech.RecognizerService/IsRecognitionAvailable"
	RecognizerService_SetRecognitionListener_FullMethodName = "/speech.RecognizerService/SetRecognitionListener"
	RecognizerService_StartListeningRaw_FullMethodName      = "/speech.RecognizerService/StartListeningRaw"
	RecognizerService_StopListeningRaw_FullMethodName       = "/speech.RecognizerService/StopListeningRaw"
	RecognizerService_CancelRaw_FullMethodName              = "/speech.RecognizerService/CancelRaw"
	RecognizerService_DestroyRaw_FullMethodName             = "/speech.RecognizerService/DestroyRaw"
)

// RecognizerServiceClient is the client API for RecognizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecognizerServiceClient interface {
	CreateRecognizer(ctx context.Context, in *CreateRecognizerRequest, opts ...grpc.CallOption) (*CreateRecognizerResponse, error)
	IsRecognitionAvailable(ctx context.Context, in *IsRecognitionAvailableRequest, opts ...grpc.CallOption) (*IsRecognitionAvailableResponse, error)
	SetRecognitionListener(ctx context.Context, in *SetRecognitionListenerRequest, opts ...grpc.CallOption) (*SetRecognitionListenerResponse, error)
	StartListeningRaw(ctx context.Context, in *StartListeningRawRequest, opts ...grpc.CallOption) (*StartListeningRawResponse, error)
	StopListeningRaw(ctx context.Context, in *StopListeningRawRequest, opts ...grpc.CallOption) (*StopListeningRawResponse, error)
	CancelRaw(ctx context.Context, in *CancelRawRequest, opts ...grpc.CallOption) (*CancelRawResponse, error)
	DestroyRaw(ctx context.Context, in *DestroyRawRequest, opts ...grpc.CallOption) (*DestroyRawResponse, error)
}

type recognizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognizerServiceClient(cc grpc.ClientConnInterface) RecognizerServiceClient {
	return &recognizerServiceClient{cc}
}

func (c *recognizerServiceClient) CreateRecognizer(ctx context.Context, in *CreateRecognizerRequest, opts ...grpc.CallOption) (*CreateRecognizerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecognizerResponse)
	err := c.cc.Invoke(ctx, RecognizerService_CreateRecognizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) IsRecognitionAvailable(ctx context.Context, in *IsRecognitionAvailableRequest, opts ...grpc.CallOption) (*IsRecognitionAvailableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsRecognitionAvailableResponse)
	err := c.cc.Invoke(ctx, RecognizerService_IsRecognitionAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) SetRecognitionListener(ctx context.Context, in *SetRecognitionListenerRequest, opts ...grpc.CallOption) (*SetRecognitionListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRecognitionListenerResponse)
	err := c.cc.Invoke(ctx, RecognizerService_SetRecognitionListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) StartListeningRaw(ctx context.Context, in *StartListeningRawRequest, opts ...grpc.CallOption) (*StartListeningRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartListeningRawResponse)
	err := c.cc.Invoke(ctx, RecognizerService_StartListeningRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) StopListeningRaw(ctx context.Context, in *StopListeningRawRequest, opts ...grpc.CallOption) (*StopListeningRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopListeningRawResponse)
	err := c.cc.Invoke(ctx, RecognizerService_StopListeningRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) CancelRaw(ctx context.Context, in *CancelRawRequest, opts ...grpc.CallOption) (*CancelRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRawResponse)
	err := c.cc.Invoke(ctx, RecognizerService_CancelRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognizerServiceClient) DestroyRaw(ctx context.Context, in *DestroyRawRequest, opts ...grpc.CallOption) (*DestroyRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyRawResponse)
	err := c.cc.Invoke(ctx, RecognizerService_DestroyRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecognizerServiceServer is the server API for RecognizerService service.
// All implementations must embed UnimplementedRecognizerServiceServer
// for forward compatibility.
type RecognizerServiceServer interface {
	CreateRecognizer(context.Context, *CreateRecognizerRequest) (*CreateRecognizerResponse, error)
	IsRecognitionAvailable(context.Context, *IsRecognitionAvailableRequest) (*IsRecognitionAvailableResponse, error)
	SetRecognitionListener(context.Context, *SetRecognitionListenerRequest) (*SetRecognitionListenerResponse, error)
	StartListeningRaw(context.Context, *StartListeningRawRequest) (*StartListeningRawResponse, error)
	StopListeningRaw(context.Context, *StopListeningRawRequest) (*StopListeningRawResponse, error)
	CancelRaw(context.Context, *CancelRawRequest) (*CancelRawResponse, error)
	DestroyRaw(context.Context, *DestroyRawRequest) (*DestroyRawResponse, error)
	mustEmbedUnimplementedRecognizerServiceServer()
}

// UnimplementedRecognizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognizerServiceServer struct{}

func (UnimplementedRecognizerServiceServer) CreateRecognizer(context.Context, *CreateRecognizerRequest) (*CreateRecognizerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRecognizer not implemented")
}
func (UnimplementedRecognizerServiceServer) IsRecognitionAvailable(context.Context, *IsRecognitionAvailableRequest) (*IsRecognitionAvailableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsRecognitionAvailable not implemented")
}
func (UnimplementedRecognizerServiceServer) SetRecognitionListener(context.Context, *SetRecognitionListenerRequest) (*SetRecognitionListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRecognitionListener not implemented")
}
func (UnimplementedRecognizerServiceServer) StartListeningRaw(context.Context, *StartListeningRawRequest) (*StartListeningRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartListeningRaw not implemented")
}
func (UnimplementedRecognizerServiceServer) StopListeningRaw(context.Context, *StopListeningRawRequest) (*StopListeningRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopListeningRaw not implemented")
}
func (UnimplementedRecognizerServiceServer) CancelRaw(context.Context, *CancelRawRequest) (*CancelRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRaw not implemented")
}
func (UnimplementedRecognizerServiceServer) DestroyRaw(context.Context, *DestroyRawRequest) (*DestroyRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyRaw not implemented")
}
func (UnimplementedRecognizerServiceServer) mustEmbedUnimplementedRecognizerServiceServer() {}
func (UnimplementedRecognizerServiceServer) testEmbeddedByValue()                           {}

// UnsafeRecognizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognizerServiceServer will
// result in compilation errors.
type UnsafeRecognizerServiceServer interface {
	mustEmbedUnimplementedRecognizerServiceServer()
}

func RegisterRecognizerServiceServer(s grpc.ServiceRegistrar, srv RecognizerServiceServer) {
	// If the following call panics, it indicates UnimplementedRecognizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecognizerService_ServiceDesc, srv)
}

func _RecognizerService_CreateRecognizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecognizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).CreateRecognizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_CreateRecognizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).CreateRecognizer(ctx, req.(*CreateRecognizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_IsRecognitionAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsRecognitionAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).IsRecognitionAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_IsRecognitionAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).IsRecognitionAvailable(ctx, req.(*IsRecognitionAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_SetRecognitionListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRecognitionListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).SetRecognitionListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_SetRecognitionListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).SetRecognitionListener(ctx, req.(*SetRecognitionListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_StartListeningRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartListeningRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).StartListeningRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_StartListeningRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).StartListeningRaw(ctx, req.(*StartListeningRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_StopListeningRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopListeningRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).StopListeningRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_StopListeningRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).StopListeningRaw(ctx, req.(*StopListeningRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_CancelRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).CancelRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_CancelRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).CancelRaw(ctx, req.(*CancelRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognizerService_DestroyRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognizerServiceServer).DestroyRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognizerService_DestroyRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognizerServiceServer).DestroyRaw(ctx, req.(*DestroyRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecognizerService_ServiceDesc is the grpc.ServiceDesc for RecognizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecognizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.RecognizerService",
	HandlerType: (*RecognizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecognizer",
			Handler:    _RecognizerService_CreateRecognizer_Handler,
		},
		{
			MethodName: "IsRecognitionAvailable",
			Handler:    _RecognizerService_IsRecognitionAvailable_Handler,
		},
		{
			MethodName: "SetRecognitionListener",
			Handler:    _RecognizerService_SetRecognitionListener_Handler,
		},
		{
			MethodName: "StartListeningRaw",
			Handler:    _RecognizerService_StartListeningRaw_Handler,
		},
		{
			MethodName: "StopListeningRaw",
			Handler:    _RecognizerService_StopListeningRaw_Handler,
		},
		{
			MethodName: "CancelRaw",
			Handler:    _RecognizerService_CancelRaw_Handler,
		},
		{
			MethodName: "DestroyRaw",
			Handler:    _RecognizerService_DestroyRaw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/speech/speech.proto",
}

const (
	TTSService_SpeakRaw_FullMethodName                          = "/speech.TTSService/SpeakRaw"
	TTSService_StopRaw_FullMethodName                           = "/speech.TTSService/StopRaw"
	TTSService_IsSpeakingRaw_FullMethodName                     = "/speech.TTSService/IsSpeakingRaw"
	TTSService_SetLanguageRaw_FullMethodName                    = "/speech.TTSService/SetLanguageRaw"
	TTSService_SetPitchRaw_FullMethodName                       = "/speech.TTSService/SetPitchRaw"
	TTSService_SetSpeechRateRaw_FullMethodName                  = "/speech.TTSService/SetSpeechRateRaw"
	TTSService_GetAvailableLanguagesRaw_FullMethodName          = "/speech.TTSService/GetAvailableLanguagesRaw"
	TTSService_ShutdownRaw_FullMethodName                       = "/speech.TTSService/ShutdownRaw"
	TTSService_SetOnUtteranceProgressListenerRaw_FullMethodName = "/speech.TTSService/SetOnUtteranceProgressListenerRaw"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSServiceClient interface {
	SpeakRaw(ctx context.Context, in *SpeakRawRequest, opts ...grpc.CallOption) (*SpeakRawResponse, error)
	StopRaw(ctx context.Context, in *StopRawRequest, opts ...grpc.CallOption) (*StopRawResponse, error)
	IsSpeakingRaw(ctx context.Context, in *IsSpeakingRawRequest, opts ...grpc.CallOption) (*IsSpeakingRawResponse, error)
	SetLanguageRaw(ctx context.Context, in *SetLanguageRawRequest, opts ...grpc.CallOption) (*SetLanguageRawResponse, error)
	SetPitchRaw(ctx context.Context, in *SetPitchRawRequest, opts ...grpc.CallOption) (*SetPitchRawResponse, error)
	SetSpeechRateRaw(ctx context.Context, in *SetSpeechRateRawRequest, opts ...grpc.CallOption) (*SetSpeechRateRawResponse, error)
	GetAvailableLanguagesRaw(ctx context.Context, in *GetAvailableLanguagesRawRequest, opts ...grpc.CallOption) (*GetAvailableLanguagesRawResponse, error)
	ShutdownRaw(ctx context.Context, in *ShutdownRawRequest, opts ...grpc.CallOption) (*ShutdownRawResponse, error)
	SetOnUtteranceProgressListenerRaw(ctx context.Context, in *SetOnUtteranceProgressListenerRawRequest, opts ...grpc.CallOption) (*SetOnUtteranceProgressListenerRawResponse, error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) SpeakRaw(ctx context.Context, in *SpeakRawRequest, opts ...grpc.CallOption) (*SpeakRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeakRawResponse)
	err := c.cc.Invoke(ctx, TTSService_SpeakRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) StopRaw(ctx context.Context, in *StopRawRequest, opts ...grpc.CallOption) (*StopRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRawResponse)
	err := c.cc.Invoke(ctx, TTSService_StopRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) IsSpeakingRaw(ctx context.Context, in *IsSpeakingRawRequest, opts ...grpc.CallOption) (*IsSpeakingRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsSpeakingRawResponse)
	err := c.cc.Invoke(ctx, TTSService_IsSpeakingRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) SetLanguageRaw(ctx context.Context, in *SetLanguageRawRequest, opts ...grpc.CallOption) (*SetLanguageRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLanguageRawResponse)
	err := c.cc.Invoke(ctx, TTSService_SetLanguageRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) SetPitchRaw(ctx context.Context, in *SetPitchRawRequest, opts ...grpc.CallOption) (*SetPitchRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPitchRawResponse)
	err := c.cc.Invoke(ctx, TTSService_SetPitchRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) SetSpeechRateRaw(ctx context.Context, in *SetSpeechRateRawRequest, opts ...grpc.CallOption) (*SetSpeechRateRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSpeechRateRawResponse)
	err := c.cc.Invoke(ctx, TTSService_SetSpeechRateRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) GetAvailableLanguagesRaw(ctx context.Context, in *GetAvailableLanguagesRawRequest, opts ...grpc.CallOption) (*GetAvailableLanguagesRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableLanguagesRawResponse)
	err := c.cc.Invoke(ctx, TTSService_GetAvailableLanguagesRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) ShutdownRaw(ctx context.Context, in *ShutdownRawRequest, opts ...grpc.CallOption) (*ShutdownRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownRawResponse)
	err := c.cc.Invoke(ctx, TTSService_ShutdownRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSServiceClient) SetOnUtteranceProgressListenerRaw(ctx context.Context, in *SetOnUtteranceProgressListenerRawRequest, opts ...grpc.CallOption) (*SetOnUtteranceProgressListenerRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOnUtteranceProgressListenerRawResponse)
	err := c.cc.Invoke(ctx, TTSService_SetOnUtteranceProgressListenerRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
type TTSServiceServer interface {
	SpeakRaw(context.Context, *SpeakRawRequest) (*SpeakRawResponse, error)
	StopRaw(context.Context, *StopRawRequest) (*StopRawResponse, error)
	IsSpeakingRaw(context.Context, *IsSpeakingRawRequest) (*IsSpeakingRawResponse, error)
	SetLanguageRaw(context.Context, *SetLanguageRawRequest) (*SetLanguageRawResponse, error)
	SetPitchRaw(context.Context, *SetPitchRawRequest) (*SetPitchRawResponse, error)
	SetSpeechRateRaw(context.Context, *SetSpeechRateRawRequest) (*SetSpeechRateRawResponse, error)
	GetAvailableLanguagesRaw(context.Context, *GetAvailableLanguagesRawRequest) (*GetAvailableLanguagesRawResponse, error)
	ShutdownRaw(context.Context, *ShutdownRawRequest) (*ShutdownRawResponse, error)
	SetOnUtteranceProgressListenerRaw(context.Context, *SetOnUtteranceProgressListenerRawRequest) (*SetOnUtteranceProgressListenerRawResponse, error)
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) SpeakRaw(context.Context, *SpeakRawRequest) (*SpeakRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeakRaw not implemented")
}
func (UnimplementedTTSServiceServer) StopRaw(context.Context, *StopRawRequest) (*StopRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRaw not implemented")
}
func (UnimplementedTTSServiceServer) IsSpeakingRaw(context.Context, *IsSpeakingRawRequest) (*IsSpeakingRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsSpeakingRaw not implemented")
}
func (UnimplementedTTSServiceServer) SetLanguageRaw(context.Context, *SetLanguageRawRequest) (*SetLanguageRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLanguageRaw not implemented")
}
func (UnimplementedTTSServiceServer) SetPitchRaw(context.Context, *SetPitchRawRequest) (*SetPitchRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPitchRaw not implemented")
}
func (UnimplementedTTSServiceServer) SetSpeechRateRaw(context.Context, *SetSpeechRateRawRequest) (*SetSpeechRateRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpeechRateRaw not implemented")
}
func (UnimplementedTTSServiceServer) GetAvailableLanguagesRaw(context.Context, *GetAvailableLanguagesRawRequest) (*GetAvailableLanguagesRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableLanguagesRaw not implemented")
}
func (UnimplementedTTSServiceServer) ShutdownRaw(context.Context, *ShutdownRawRequest) (*ShutdownRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownRaw not implemented")
}
func (UnimplementedTTSServiceServer) SetOnUtteranceProgressListenerRaw(context.Context, *SetOnUtteranceProgressListenerRawRequest) (*SetOnUtteranceProgressListenerRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOnUtteranceProgressListenerRaw not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call panics, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_SpeakRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeakRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).SpeakRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_SpeakRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).SpeakRaw(ctx, req.(*SpeakRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_StopRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).StopRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_StopRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).StopRaw(ctx, req.(*StopRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_IsSpeakingRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSpeakingRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).IsSpeakingRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_IsSpeakingRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).IsSpeakingRaw(ctx, req.(*IsSpeakingRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_SetLanguageRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLanguageRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).SetLanguageRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_SetLanguageRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).SetLanguageRaw(ctx, req.(*SetLanguageRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_SetPitchRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPitchRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).SetPitchRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_SetPitchRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).SetPitchRaw(ctx, req.(*SetPitchRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_SetSpeechRateRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpeechRateRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).SetSpeechRateRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_SetSpeechRateRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).SetSpeechRateRaw(ctx, req.(*SetSpeechRateRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_GetAvailableLanguagesRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableLanguagesRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).GetAvailableLanguagesRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_GetAvailableLanguagesRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).GetAvailableLanguagesRaw(ctx, req.(*GetAvailableLanguagesRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_ShutdownRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).ShutdownRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_ShutdownRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).ShutdownRaw(ctx, req.(*ShutdownRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSService_SetOnUtteranceProgressListenerRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOnUtteranceProgressListenerRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).SetOnUtteranceProgressListenerRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_SetOnUtteranceProgressListenerRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).SetOnUtteranceProgressListenerRaw(ctx, req.(*SetOnUtteranceProgressListenerRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpeakRaw",
			Handler:    _TTSService_SpeakRaw_Handler,
		},
		{
			MethodName: "StopRaw",
			Handler:    _TTSService_StopRaw_Handler,
		},
		{
			MethodName: "IsSpeakingRaw",
			Handler:    _TTSService_IsSpeakingRaw_Handler,
		},
		{
			MethodName: "SetLanguageRaw",
			Handler:    _TTSService_SetLanguageRaw_Handler,
		},
		{
			MethodName: "SetPitchRaw",
			Handler:    _TTSService_SetPitchRaw_Handler,
		},
		{
			MethodName: "SetSpeechRateRaw",
			Handler:    _TTSService_SetSpeechRateRaw_Handler,
		},
		{
			MethodName: "GetAvailableLanguagesRaw",
			Handler:    _TTSService_GetAvailableLanguagesRaw_Handler,
		},
		{
			MethodName: "ShutdownRaw",
			Handler:    _TTSService_ShutdownRaw_Handler,
		},
		{
			MethodName: "SetOnUtteranceProgressListenerRaw",
			Handler:    _TTSService_SetOnUtteranceProgressListenerRaw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/speech/speech.proto",
}

const (
	RecognitionListenerService_SubscribeRecognitionListener_FullMethodName = "/speech.RecognitionListenerService/SubscribeRecognitionListener"
)

// RecognitionListenerServiceClient is the client API for RecognitionListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecognitionListenerServiceClient interface {
	// Server-streaming events from android.speech.RecognitionListener
	SubscribeRecognitionListener(ctx context.Context, in *SubscribeRecognitionListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecognitionListenerEvent], error)
}

type recognitionListenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognitionListenerServiceClient(cc grpc.ClientConnInterface) RecognitionListenerServiceClient {
	return &recognitionListenerServiceClient{cc}
}

func (c *recognitionListenerServiceClient) SubscribeRecognitionListener(ctx context.Context, in *SubscribeRecognitionListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecognitionListenerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecognitionListenerService_ServiceDesc.Streams[0], RecognitionListenerService_SubscribeRecognitionListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRecognitionListenerRequest, RecognitionListenerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecognitionListenerService_SubscribeRecognitionListenerClient = grpc.ServerStreamingClient[RecognitionListenerEvent]

// RecognitionListenerServiceServer is the server API for RecognitionListenerService service.
// All implementations must embed UnimplementedRecognitionListenerServiceServer
// for forward compatibility.
type RecognitionListenerServiceServer interface {
	// Server-streaming events from android.speech.RecognitionListener
	SubscribeRecognitionListener(*SubscribeRecognitionListenerRequest, grpc.ServerStreamingServer[RecognitionListenerEvent]) error
	mustEmbedUnimplementedRecognitionListenerServiceServer()
}

// UnimplementedRecognitionListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognitionListenerServiceServer struct{}

func (UnimplementedRecognitionListenerServiceServer) SubscribeRecognitionListener(*SubscribeRecognitionListenerRequest, grpc.ServerStreamingServer[RecognitionListenerEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRecognitionListener not implemented")
}
func (UnimplementedRecognitionListenerServiceServer) mustEmbedUnimplementedRecognitionListenerServiceServer() {
}
func (UnimplementedRecognitionListenerServiceServer) testEmbeddedByValue() {}

// UnsafeRecognitionListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognitionListenerServiceServer will
// result in compilation errors.
type UnsafeRecognitionListenerServiceServer interface {
	mustEmbedUnimplementedRecognitionListenerServiceServer()
}

func RegisterRecognitionListenerServiceServer(s grpc.ServiceRegistrar, srv RecognitionListenerServiceServer) {
	// If the following call panics, it indicates UnimplementedRecognitionListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecognitionListenerService_ServiceDesc, srv)
}

func _RecognitionListenerService_SubscribeRecognitionListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRecognitionListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecognitionListenerServiceServer).SubscribeRecognitionListener(m, &grpc.GenericServerStream[SubscribeRecognitionListenerRequest, RecognitionListenerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecognitionListenerService_SubscribeRecognitionListenerServer = grpc.ServerStreamingServer[RecognitionListenerEvent]

// RecognitionListenerService_ServiceDesc is the grpc.ServiceDesc for RecognitionListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecognitionListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.RecognitionListenerService",
	HandlerType: (*RecognitionListenerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRecognitionListener",
			Handler:       _RecognitionListenerService_SubscribeRecognitionListener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/speech/speech.proto",
}

const (
	TtsOnInitListenerService_SubscribeTtsOnInitListener_FullMethodName = "/speech.TtsOnInitListenerService/SubscribeTtsOnInitListener"
)

// TtsOnInitListenerServiceClient is the client API for TtsOnInitListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TtsOnInitListenerServiceClient interface {
	// Server-streaming events from android.speech.tts.TextToSpeech$OnInitListener
	SubscribeTtsOnInitListener(ctx context.Context, in *SubscribeTtsOnInitListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TtsOnInitListenerEvent], error)
}

type ttsOnInitListenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTtsOnInitListenerServiceClient(cc grpc.ClientConnInterface) TtsOnInitListenerServiceClient {
	return &ttsOnInitListenerServiceClient{cc}
}

func (c *ttsOnInitListenerServiceClient) SubscribeTtsOnInitListener(ctx context.Context, in *SubscribeTtsOnInitListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TtsOnInitListenerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TtsOnInitListenerService_ServiceDesc.Streams[0], TtsOnInitListenerService_SubscribeTtsOnInitListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTtsOnInitListenerRequest, TtsOnInitListenerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TtsOnInitListenerService_SubscribeTtsOnInitListenerClient = grpc.ServerStreamingClient[TtsOnInitListenerEvent]

// TtsOnInitListenerServiceServer is the server API for TtsOnInitListenerService service.
// All implementations must embed UnimplementedTtsOnInitListenerServiceServer
// for forward compatibility.
type TtsOnInitListenerServiceServer interface {
	// Server-streaming events from android.speech.tts.TextToSpeech$OnInitListener
	SubscribeTtsOnInitListener(*SubscribeTtsOnInitListenerRequest, grpc.ServerStreamingServer[TtsOnInitListenerEvent]) error
	mustEmbedUnimplementedTtsOnInitListenerServiceServer()
}

// UnimplementedTtsOnInitListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTtsOnInitListenerServiceServer struct{}

func (UnimplementedTtsOnInitListenerServiceServer) SubscribeTtsOnInitListener(*SubscribeTtsOnInitListenerRequest, grpc.ServerStreamingServer[TtsOnInitListenerEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTtsOnInitListener not implemented")
}
func (UnimplementedTtsOnInitListenerServiceServer) mustEmbedUnimplementedTtsOnInitListenerServiceServer() {
}
func (UnimplementedTtsOnInitListenerServiceServer) testEmbeddedByValue() {}

// UnsafeTtsOnInitListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TtsOnInitListenerServiceServer will
// result in compilation errors.
type UnsafeTtsOnInitListenerServiceServer interface {
	mustEmbedUnimplementedTtsOnInitListenerServiceServer()
}

func RegisterTtsOnInitListenerServiceServer(s grpc.ServiceRegistrar, srv TtsOnInitListenerServiceServer) {
	// If the following call panics, it indicates UnimplementedTtsOnInitListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TtsOnInitListenerService_ServiceDesc, srv)
}

func _TtsOnInitListenerService_SubscribeTtsOnInitListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTtsOnInitListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TtsOnInitListenerServiceServer).SubscribeTtsOnInitListener(m, &grpc.GenericServerStream[SubscribeTtsOnInitListenerRequest, TtsOnInitListenerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TtsOnInitListenerService_SubscribeTtsOnInitListenerServer = grpc.ServerStreamingServer[TtsOnInitListenerEvent]

// TtsOnInitListenerService_ServiceDesc is the grpc.ServiceDesc for TtsOnInitListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TtsOnInitListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.TtsOnInitListenerService",
	HandlerType: (*TtsOnInitListenerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTtsOnInitListener",
			Handler:       _TtsOnInitListenerService_SubscribeTtsOnInitListener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/speech/speech.proto",
}

const (
	UtteranceProgressListenerService_SubscribeUtteranceProgressListener_FullMethodName = "/speech.UtteranceProgressListenerService/SubscribeUtteranceProgressListener"
)

// UtteranceProgressListenerServiceClient is the client API for UtteranceProgressListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UtteranceProgressListenerServiceClient interface {
	// Server-streaming events from android.speech.tts.UtteranceProgressListener
	SubscribeUtteranceProgressListener(ctx context.Context, in *SubscribeUtteranceProgressListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UtteranceProgressListenerEvent], error)
}

type utteranceProgressListenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUtteranceProgressListenerServiceClient(cc grpc.ClientConnInterface) UtteranceProgressListenerServiceClient {
	return &utteranceProgressListenerServiceClient{cc}
}

func (c *utteranceProgressListenerServiceClient) SubscribeUtteranceProgressListener(ctx context.Context, in *SubscribeUtteranceProgressListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UtteranceProgressListenerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UtteranceProgressListenerService_ServiceDesc.Streams[0], UtteranceProgressListenerService_SubscribeUtteranceProgressListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeUtteranceProgressListenerRequest, UtteranceProgressListenerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UtteranceProgressListenerService_SubscribeUtteranceProgressListenerClient = grpc.ServerStreamingClient[UtteranceProgressListenerEvent]

// UtteranceProgressListenerServiceServer is the server API for UtteranceProgressListenerService service.
// All implementations must embed UnimplementedUtteranceProgressListenerServiceServer
// for forward compatibility.
type UtteranceProgressListenerServiceServer interface {
	// Server-streaming events from android.speech.tts.UtteranceProgressListener
	SubscribeUtteranceProgressListener(*SubscribeUtteranceProgressListenerRequest, grpc.ServerStreamingServer[UtteranceProgressListenerEvent]) error
	mustEmbedUnimplementedUtteranceProgressListenerServiceServer()
}

// UnimplementedUtteranceProgressListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUtteranceProgressListenerServiceServer struct{}

func (UnimplementedUtteranceProgressListenerServiceServer) SubscribeUtteranceProgressListener(*SubscribeUtteranceProgressListenerRequest, grpc.ServerStreamingServer[UtteranceProgressListenerEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeUtteranceProgressListener not implemented")
}
func (UnimplementedUtteranceProgressListenerServiceServer) mustEmbedUnimplementedUtteranceProgressListenerServiceServer() {
}
func (UnimplementedUtteranceProgressListenerServiceServer) testEmbeddedByValue() {}

// UnsafeUtteranceProgressListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UtteranceProgressListenerServiceServer will
// result in compilation errors.
type UnsafeUtteranceProgressListenerServiceServer interface {
	mustEmbedUnimplementedUtteranceProgressListenerServiceServer()
}

func RegisterUtteranceProgressListenerServiceServer(s grpc.ServiceRegistrar, srv UtteranceProgressListenerServiceServer) {
	// If the following call panics, it indicates UnimplementedUtteranceProgressListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UtteranceProgressListenerService_ServiceDesc, srv)
}

func _UtteranceProgressListenerService_SubscribeUtteranceProgressListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeUtteranceProgressListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UtteranceProgressListenerServiceServer).SubscribeUtteranceProgressListener(m, &grpc.GenericServerStream[SubscribeUtteranceProgressListenerRequest, UtteranceProgressListenerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UtteranceProgressListenerService_SubscribeUtteranceProgressListenerServer = grpc.ServerStreamingServer[UtteranceProgressListenerEvent]

// UtteranceProgressListenerService_ServiceDesc is the grpc.ServiceDesc for UtteranceProgressListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UtteranceProgressListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.UtteranceProgressListenerService",
	HandlerType: (*UtteranceProgressListenerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeUtteranceProgressListener",
			Handler:       _UtteranceProgressListenerService_SubscribeUtteranceProgressListener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/speech/speech.proto",
}
