// Code generated by javagen. DO NOT EDIT.

package pm

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ApplicationInfoDisplayNameComparator wraps android.content.pm.ApplicationInfo$DisplayNameComparator.
type ApplicationInfoDisplayNameComparator struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Compare2 calls android.content.pm.ApplicationInfo$DisplayNameComparator.compare.
func (m *ApplicationInfoDisplayNameComparator) Compare2(arg0 *jni.Object, arg1 *jni.Object) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midApplicationInfoDisplayNameComparatorCompare2 == nil {
			callErr = fmt.Errorf("android.content.pm.ApplicationInfo$DisplayNameComparator.compare is not available on this device")
			return callErr
		}

		result, callErr = env.CallIntMethod(
			m.Obj,
			midApplicationInfoDisplayNameComparatorCompare2, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Compare2_1 calls android.content.pm.ApplicationInfo$DisplayNameComparator.compare.
func (m *ApplicationInfoDisplayNameComparator) Compare2_1(arg0 *jni.Object, arg1 *jni.Object) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midApplicationInfoDisplayNameComparatorCompare2_1 == nil {
			callErr = fmt.Errorf("android.content.pm.ApplicationInfo$DisplayNameComparator.compare is not available on this device")
			return callErr
		}

		result, callErr = env.CallIntMethod(
			m.Obj,
			midApplicationInfoDisplayNameComparatorCompare2_1, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
