// Code generated by javagen. DO NOT EDIT.

package pm

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// LauncherAppsShortcutQuery wraps android.content.pm.LauncherApps$ShortcutQuery.
type LauncherAppsShortcutQuery struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// SetActivity calls android.content.pm.LauncherApps$ShortcutQuery.setActivity.
func (m *LauncherAppsShortcutQuery) SetActivity(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShortcutQuerySetActivity == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps$ShortcutQuery.setActivity is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsShortcutQuerySetActivity, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetChangedSince calls android.content.pm.LauncherApps$ShortcutQuery.setChangedSince.
func (m *LauncherAppsShortcutQuery) SetChangedSince(arg0 int64) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShortcutQuerySetChangedSince == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps$ShortcutQuery.setChangedSince is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsShortcutQuerySetChangedSince, jni.LongValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetPackage calls android.content.pm.LauncherApps$ShortcutQuery.setPackage.
func (m *LauncherAppsShortcutQuery) SetPackage(arg0 string) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShortcutQuerySetPackage == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps$ShortcutQuery.setPackage is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsShortcutQuerySetPackage, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetQueryFlags calls android.content.pm.LauncherApps$ShortcutQuery.setQueryFlags.
func (m *LauncherAppsShortcutQuery) SetQueryFlags(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShortcutQuerySetQueryFlags == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps$ShortcutQuery.setQueryFlags is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsShortcutQuerySetQueryFlags, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.content.pm.LauncherApps$ShortcutQuery.toString.
func (m *LauncherAppsShortcutQuery) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShortcutQueryToString == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps$ShortcutQuery.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsShortcutQueryToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
