// Code generated by javagen. DO NOT EDIT.

package pm

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

const serviceNameLauncherApps = "launcherapps"

// LauncherApps wraps android.content.pm.LauncherApps.
type LauncherApps struct {
	VM  *jni.VM
	Ctx *app.Context
	Obj *jni.GlobalRef
}

// NewLauncherApps obtains android.content.pm.LauncherApps from the Android system service manager.
func NewLauncherApps(ctx *app.Context) (*LauncherApps, error) {
	if ctx == nil {
		return nil, fmt.Errorf("LauncherApps: nil Context")
	}
	var mgr LauncherApps
	mgr.VM = ctx.VM
	mgr.Ctx = ctx

	err := mgr.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		svc, err := ctx.GetSystemService(serviceNameLauncherApps)
		if err != nil {
			return err
		}
		if svc == nil || svc.Ref() == 0 {
			return fmt.Errorf("%s service not available", serviceNameLauncherApps)
		}
		// GetSystemService already returns a GlobalRef, so use it directly
		// instead of wrapping again (which would leak the original).
		mgr.Obj = svc
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &mgr, nil
}

// Close releases the global reference to the underlying Java object.
// After Close, the LauncherApps must not be used.
func (m *LauncherApps) Close() {
	if m.Obj != nil {
		m.VM.Do(func(env *jni.Env) error {
			env.DeleteGlobalRef(m.Obj)
			m.Obj = nil
			return nil
		})
	}
}

// GetAppMarketActivityIntent calls android.content.pm.LauncherApps.getAppMarketActivityIntent.
func (m *LauncherApps) GetAppMarketActivityIntent(arg0 string, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetAppMarketActivityIntent == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getAppMarketActivityIntent is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetAppMarketActivityIntent, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetApplicationInfo calls android.content.pm.LauncherApps.getApplicationInfo.
func (m *LauncherApps) GetApplicationInfo(
	arg0 string,
	arg1 int32,
	arg2 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetApplicationInfo == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getApplicationInfo is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetApplicationInfo, jni.ObjectValue(&jArg0.Object), jni.IntValue(arg1), jni.ObjectValue(arg2),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetLauncherUserInfo calls android.content.pm.LauncherApps.getLauncherUserInfo.
func (m *LauncherApps) GetLauncherUserInfo(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetLauncherUserInfo == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getLauncherUserInfo is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetLauncherUserInfo, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetPinItemRequest calls android.content.pm.LauncherApps.getPinItemRequest.
func (m *LauncherApps) GetPinItemRequest(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetPinItemRequest == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getPinItemRequest is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetPinItemRequest, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetPrivateSpaceSettingsIntent calls android.content.pm.LauncherApps.getPrivateSpaceSettingsIntent.
func (m *LauncherApps) GetPrivateSpaceSettingsIntent() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetPrivateSpaceSettingsIntent == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getPrivateSpaceSettingsIntent is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetPrivateSpaceSettingsIntent,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetShortcutBadgedIconDrawable calls android.content.pm.LauncherApps.getShortcutBadgedIconDrawable.
func (m *LauncherApps) GetShortcutBadgedIconDrawable(arg0 *jni.Object, arg1 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetShortcutBadgedIconDrawable == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getShortcutBadgedIconDrawable is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetShortcutBadgedIconDrawable, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetShortcutConfigActivityIntent calls android.content.pm.LauncherApps.getShortcutConfigActivityIntent.
func (m *LauncherApps) GetShortcutConfigActivityIntent(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetShortcutConfigActivityIntent == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getShortcutConfigActivityIntent is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetShortcutConfigActivityIntent, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetShortcutIconDrawable calls android.content.pm.LauncherApps.getShortcutIconDrawable.
func (m *LauncherApps) GetShortcutIconDrawable(arg0 *jni.Object, arg1 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetShortcutIconDrawable == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getShortcutIconDrawable is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetShortcutIconDrawable, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetShortcutIntent calls android.content.pm.LauncherApps.getShortcutIntent.
func (m *LauncherApps) GetShortcutIntent(
	arg0 string,
	arg1 string,
	arg2 *jni.Object,
	arg3 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetShortcutIntent == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getShortcutIntent is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		jArg1, err := env.NewStringUTF(arg1)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg1.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetShortcutIntent, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(&jArg1.Object), jni.ObjectValue(arg2), jni.ObjectValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetSuspendedPackageLauncherExtras calls android.content.pm.LauncherApps.getSuspendedPackageLauncherExtras.
func (m *LauncherApps) GetSuspendedPackageLauncherExtras(arg0 string, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsGetSuspendedPackageLauncherExtras == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.getSuspendedPackageLauncherExtras is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsGetSuspendedPackageLauncherExtras, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// HasShortcutHostPermission calls android.content.pm.LauncherApps.hasShortcutHostPermission.
func (m *LauncherApps) HasShortcutHostPermission() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsHasShortcutHostPermission == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.hasShortcutHostPermission is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midLauncherAppsHasShortcutHostPermission,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsActivityEnabled calls android.content.pm.LauncherApps.isActivityEnabled.
func (m *LauncherApps) IsActivityEnabled(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsIsActivityEnabled == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.isActivityEnabled is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midLauncherAppsIsActivityEnabled, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsPackageEnabled calls android.content.pm.LauncherApps.isPackageEnabled.
func (m *LauncherApps) IsPackageEnabled(arg0 string, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsIsPackageEnabled == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.isPackageEnabled is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midLauncherAppsIsPackageEnabled, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// RegisterCallback calls android.content.pm.LauncherApps.registerCallback.
func (m *LauncherApps) RegisterCallback(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsRegisterCallback == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.registerCallback is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsRegisterCallback, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// RegisterPackageInstallerSessionCallback calls android.content.pm.LauncherApps.registerPackageInstallerSessionCallback.
func (m *LauncherApps) RegisterPackageInstallerSessionCallback(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsRegisterPackageInstallerSessionCallback == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.registerPackageInstallerSessionCallback is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsRegisterPackageInstallerSessionCallback, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ResolveActivity calls android.content.pm.LauncherApps.resolveActivity.
func (m *LauncherApps) ResolveActivity(arg0 *jni.Object, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsResolveActivity == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.resolveActivity is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherAppsResolveActivity, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetArchiveCompatibility calls android.content.pm.LauncherApps.setArchiveCompatibility.
func (m *LauncherApps) SetArchiveCompatibility(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsSetArchiveCompatibility == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.setArchiveCompatibility is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsSetArchiveCompatibility, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ShouldHideFromSuggestions calls android.content.pm.LauncherApps.shouldHideFromSuggestions.
func (m *LauncherApps) ShouldHideFromSuggestions(arg0 string, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsShouldHideFromSuggestions == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.shouldHideFromSuggestions is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midLauncherAppsShouldHideFromSuggestions, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// StartAppDetailsActivity calls android.content.pm.LauncherApps.startAppDetailsActivity.
func (m *LauncherApps) StartAppDetailsActivity(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsStartAppDetailsActivity == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.startAppDetailsActivity is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsStartAppDetailsActivity, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// StartMainActivity calls android.content.pm.LauncherApps.startMainActivity.
func (m *LauncherApps) StartMainActivity(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
	arg3 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsStartMainActivity == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.startMainActivity is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsStartMainActivity, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2), jni.ObjectValue(arg3),
		)
		return callErr
	})
	return callErr
}

// StartPackageInstallerSessionDetailsActivity calls android.content.pm.LauncherApps.startPackageInstallerSessionDetailsActivity.
func (m *LauncherApps) StartPackageInstallerSessionDetailsActivity(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsStartPackageInstallerSessionDetailsActivity == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.startPackageInstallerSessionDetailsActivity is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsStartPackageInstallerSessionDetailsActivity, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		return callErr
	})
	return callErr
}

// StartShortcut3 calls android.content.pm.LauncherApps.startShortcut.
func (m *LauncherApps) StartShortcut3(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsStartShortcut3 == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.startShortcut is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsStartShortcut3, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		return callErr
	})
	return callErr
}

// StartShortcut5_1 calls android.content.pm.LauncherApps.startShortcut.
func (m *LauncherApps) StartShortcut5_1(
	arg0 string,
	arg1 string,
	arg2 *jni.Object,
	arg3 *jni.Object,
	arg4 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsStartShortcut5_1 == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.startShortcut is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		jArg1, err := env.NewStringUTF(arg1)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg1.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsStartShortcut5_1, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(&jArg1.Object), jni.ObjectValue(arg2), jni.ObjectValue(arg3), jni.ObjectValue(arg4),
		)
		return callErr
	})
	return callErr
}

// UnregisterCallback calls android.content.pm.LauncherApps.unregisterCallback.
func (m *LauncherApps) UnregisterCallback(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsUnregisterCallback == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.unregisterCallback is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsUnregisterCallback, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// UnregisterPackageInstallerSessionCallback calls android.content.pm.LauncherApps.unregisterPackageInstallerSessionCallback.
func (m *LauncherApps) UnregisterPackageInstallerSessionCallback(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherAppsUnregisterPackageInstallerSessionCallback == nil {
			callErr = fmt.Errorf("android.content.pm.LauncherApps.unregisterPackageInstallerSessionCallback is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherAppsUnregisterPackageInstallerSessionCallback, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}
