// Code generated by javagen. DO NOT EDIT.

package pm

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PackageInstallerSessionParams wraps android.content.pm.PackageInstaller$SessionParams.
type PackageInstallerSessionParams struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.content.pm.PackageInstaller$SessionParams.describeContents.
func (m *PackageInstallerSessionParams) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsDescribeContents == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midPackageInstallerSessionParamsDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// SetAppIcon calls android.content.pm.PackageInstaller$SessionParams.setAppIcon.
func (m *PackageInstallerSessionParams) SetAppIcon(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetAppIcon == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setAppIcon is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetAppIcon, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetAppLabel calls android.content.pm.PackageInstaller$SessionParams.setAppLabel.
func (m *PackageInstallerSessionParams) SetAppLabel(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetAppLabel == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setAppLabel is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetAppLabel, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// SetAppPackageName calls android.content.pm.PackageInstaller$SessionParams.setAppPackageName.
func (m *PackageInstallerSessionParams) SetAppPackageName(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetAppPackageName == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setAppPackageName is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetAppPackageName, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// SetApplicationEnabledSettingPersistent calls android.content.pm.PackageInstaller$SessionParams.setApplicationEnabledSettingPersistent.
func (m *PackageInstallerSessionParams) SetApplicationEnabledSettingPersistent() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetApplicationEnabledSettingPersistent == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setApplicationEnabledSettingPersistent is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetApplicationEnabledSettingPersistent,
		)
		return callErr
	})
	return callErr
}

// SetAutoInstallDependenciesEnabled calls android.content.pm.PackageInstaller$SessionParams.setAutoInstallDependenciesEnabled.
func (m *PackageInstallerSessionParams) SetAutoInstallDependenciesEnabled(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetAutoInstallDependenciesEnabled == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setAutoInstallDependenciesEnabled is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetAutoInstallDependenciesEnabled, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// SetAutoRevokePermissionsMode calls android.content.pm.PackageInstaller$SessionParams.setAutoRevokePermissionsMode.
func (m *PackageInstallerSessionParams) SetAutoRevokePermissionsMode(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetAutoRevokePermissionsMode == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setAutoRevokePermissionsMode is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetAutoRevokePermissionsMode, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// SetDontKillApp calls android.content.pm.PackageInstaller$SessionParams.setDontKillApp.
func (m *PackageInstallerSessionParams) SetDontKillApp(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetDontKillApp == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setDontKillApp is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetDontKillApp, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// SetInstallLocation calls android.content.pm.PackageInstaller$SessionParams.setInstallLocation.
func (m *PackageInstallerSessionParams) SetInstallLocation(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetInstallLocation == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setInstallLocation is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetInstallLocation, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetInstallReason calls android.content.pm.PackageInstaller$SessionParams.setInstallReason.
func (m *PackageInstallerSessionParams) SetInstallReason(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetInstallReason == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setInstallReason is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetInstallReason, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetInstallScenario calls android.content.pm.PackageInstaller$SessionParams.setInstallScenario.
func (m *PackageInstallerSessionParams) SetInstallScenario(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetInstallScenario == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setInstallScenario is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetInstallScenario, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetInstallerPackageName calls android.content.pm.PackageInstaller$SessionParams.setInstallerPackageName.
func (m *PackageInstallerSessionParams) SetInstallerPackageName(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetInstallerPackageName == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setInstallerPackageName is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetInstallerPackageName, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// SetMultiPackage calls android.content.pm.PackageInstaller$SessionParams.setMultiPackage.
func (m *PackageInstallerSessionParams) SetMultiPackage() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetMultiPackage == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setMultiPackage is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetMultiPackage,
		)
		return callErr
	})
	return callErr
}

// SetOriginatingUid calls android.content.pm.PackageInstaller$SessionParams.setOriginatingUid.
func (m *PackageInstallerSessionParams) SetOriginatingUid(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetOriginatingUid == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setOriginatingUid is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetOriginatingUid, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetOriginatingUri calls android.content.pm.PackageInstaller$SessionParams.setOriginatingUri.
func (m *PackageInstallerSessionParams) SetOriginatingUri(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetOriginatingUri == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setOriginatingUri is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetOriginatingUri, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetPackageSource calls android.content.pm.PackageInstaller$SessionParams.setPackageSource.
func (m *PackageInstallerSessionParams) SetPackageSource(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetPackageSource == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setPackageSource is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetPackageSource, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetPermissionState calls android.content.pm.PackageInstaller$SessionParams.setPermissionState.
func (m *PackageInstallerSessionParams) SetPermissionState(arg0 string, arg1 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetPermissionState == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setPermissionState is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetPermissionState, jni.ObjectValue(&jArg0.Object), jni.IntValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetReferrerUri calls android.content.pm.PackageInstaller$SessionParams.setReferrerUri.
func (m *PackageInstallerSessionParams) SetReferrerUri(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetReferrerUri == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setReferrerUri is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetReferrerUri, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetRequestUpdateOwnership calls android.content.pm.PackageInstaller$SessionParams.setRequestUpdateOwnership.
func (m *PackageInstallerSessionParams) SetRequestUpdateOwnership(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetRequestUpdateOwnership == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setRequestUpdateOwnership is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetRequestUpdateOwnership, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// SetRequireUserAction calls android.content.pm.PackageInstaller$SessionParams.setRequireUserAction.
func (m *PackageInstallerSessionParams) SetRequireUserAction(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetRequireUserAction == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setRequireUserAction is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetRequireUserAction, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetSize calls android.content.pm.PackageInstaller$SessionParams.setSize.
func (m *PackageInstallerSessionParams) SetSize(arg0 int64) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetSize == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setSize is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetSize, jni.LongValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetUnarchiveId calls android.content.pm.PackageInstaller$SessionParams.setUnarchiveId.
func (m *PackageInstallerSessionParams) SetUnarchiveId(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsSetUnarchiveId == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.setUnarchiveId is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsSetUnarchiveId, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// WriteToParcel calls android.content.pm.PackageInstaller$SessionParams.writeToParcel.
func (m *PackageInstallerSessionParams) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsWriteToParcel == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPackageInstallerSessionParamsWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.content.pm.PackageInstaller$SessionParams.toString.
func (m *PackageInstallerSessionParams) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPackageInstallerSessionParamsToString == nil {
			callErr = fmt.Errorf("android.content.pm.PackageInstaller$SessionParams.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midPackageInstallerSessionParamsToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
