// Code generated by javagen. DO NOT EDIT.

package sqlite

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// SQLiteDatabaseCursorFactory wraps android.database.sqlite.SQLiteDatabase$CursorFactory.
type SQLiteDatabaseCursorFactory struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewCursor calls android.database.sqlite.SQLiteDatabase$CursorFactory.newCursor.
func (m *SQLiteDatabaseCursorFactory) NewCursor(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 string,
	arg3 *jni.Object,
) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSQLiteDatabaseCursorFactoryNewCursor == nil {
			callErr = fmt.Errorf("android.database.sqlite.SQLiteDatabase$CursorFactory.newCursor is not available on this device")
			return callErr
		}

		jArg2, err := env.NewStringUTF(arg2)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg2.Object)

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midSQLiteDatabaseCursorFactoryNewCursor, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(&jArg2.Object), jni.ObjectValue(arg3),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
