// Code generated by javagen. DO NOT EDIT.

package text

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// AlphabeticIndexImmutableIndex wraps android.icu.text.AlphabeticIndex$ImmutableIndex.
type AlphabeticIndexImmutableIndex struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetBucketCount calls android.icu.text.AlphabeticIndex$ImmutableIndex.getBucketCount.
func (m *AlphabeticIndexImmutableIndex) GetBucketCount() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlphabeticIndexImmutableIndexGetBucketCount == nil {
			callErr = fmt.Errorf("android.icu.text.AlphabeticIndex$ImmutableIndex.getBucketCount is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midAlphabeticIndexImmutableIndexGetBucketCount,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetBucketIndex calls android.icu.text.AlphabeticIndex$ImmutableIndex.getBucketIndex.
func (m *AlphabeticIndexImmutableIndex) GetBucketIndex(arg0 string) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midAlphabeticIndexImmutableIndexGetBucketIndex == nil {
			callErr = fmt.Errorf("android.icu.text.AlphabeticIndex$ImmutableIndex.getBucketIndex is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallIntMethod(
			m.Obj,
			midAlphabeticIndexImmutableIndexGetBucketIndex, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
