// Code generated by grpcgen. DO NOT EDIT.

package audiomanager

import (
	"context"

	"github.com/xaionaro-go/jni"

	"github.com/xaionaro-go/jni/app"
	"github.com/xaionaro-go/jni/handlestore"
	jnipkg "github.com/xaionaro-go/jni/media/audiomanager"
	pb "github.com/xaionaro-go/jni/proto/audiomanager"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// audioManagerServer implements pb.AudioManagerServiceServer.
type audioManagerServer struct {
	pb.UnimplementedAudioManagerServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *audioManagerServer) AbandonAudioFocus(_ context.Context, req *pb.AbandonAudioFocusRequest) (*pb.AbandonAudioFocusResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.AbandonAudioFocus(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AbandonAudioFocusResponse{Result: result}, nil
}

func (s *audioManagerServer) AbandonAudioFocusRequestOp(_ context.Context, req *pb.AbandonAudioFocusRequestOpRequest) (*pb.AbandonAudioFocusRequestOpResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.AbandonAudioFocusRequest(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AbandonAudioFocusRequestOpResponse{Result: result}, nil
}

func (s *audioManagerServer) AddOnCommunicationDeviceChangedListener(_ context.Context, req *pb.AddOnCommunicationDeviceChangedListenerRequest) (*pb.AddOnCommunicationDeviceChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AddOnCommunicationDeviceChangedListener(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AddOnCommunicationDeviceChangedListenerResponse{}, nil
}

func (s *audioManagerServer) AddOnModeChangedListener(_ context.Context, req *pb.AddOnModeChangedListenerRequest) (*pb.AddOnModeChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AddOnModeChangedListener(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AddOnModeChangedListenerResponse{}, nil
}

func (s *audioManagerServer) AddOnPreferredMixerAttributesChangedListener(_ context.Context, req *pb.AddOnPreferredMixerAttributesChangedListenerRequest) (*pb.AddOnPreferredMixerAttributesChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AddOnPreferredMixerAttributesChangedListener(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AddOnPreferredMixerAttributesChangedListenerResponse{}, nil
}

func (s *audioManagerServer) AdjustStreamVolume(_ context.Context, req *pb.AdjustStreamVolumeRequest) (*pb.AdjustStreamVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AdjustStreamVolume(req.GetArg0(), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AdjustStreamVolumeResponse{}, nil
}

func (s *audioManagerServer) AdjustSuggestedStreamVolume(_ context.Context, req *pb.AdjustSuggestedStreamVolumeRequest) (*pb.AdjustSuggestedStreamVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AdjustSuggestedStreamVolume(req.GetArg0(), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AdjustSuggestedStreamVolumeResponse{}, nil
}

func (s *audioManagerServer) AdjustVolume(_ context.Context, req *pb.AdjustVolumeRequest) (*pb.AdjustVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AdjustVolume(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AdjustVolumeResponse{}, nil
}

func (s *audioManagerServer) AdjustVolumeGroupVolume(_ context.Context, req *pb.AdjustVolumeGroupVolumeRequest) (*pb.AdjustVolumeGroupVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.AdjustVolumeGroupVolume(req.GetArg0(), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.AdjustVolumeGroupVolumeResponse{}, nil
}

func (s *audioManagerServer) ClearCommunicationDevice(_ context.Context, req *pb.ClearCommunicationDeviceRequest) (*pb.ClearCommunicationDeviceResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.ClearCommunicationDevice(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ClearCommunicationDeviceResponse{}, nil
}

func (s *audioManagerServer) ClearPreferredMixerAttributes(_ context.Context, req *pb.ClearPreferredMixerAttributesRequest) (*pb.ClearPreferredMixerAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.ClearPreferredMixerAttributes(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ClearPreferredMixerAttributesResponse{Result: result}, nil
}

func (s *audioManagerServer) DispatchMediaKeyEvent(_ context.Context, req *pb.DispatchMediaKeyEventRequest) (*pb.DispatchMediaKeyEventResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.DispatchMediaKeyEvent(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DispatchMediaKeyEventResponse{}, nil
}

func (s *audioManagerServer) GenerateAudioSessionId(_ context.Context, req *pb.GenerateAudioSessionIdRequest) (*pb.GenerateAudioSessionIdResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GenerateAudioSessionId()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GenerateAudioSessionIdResponse{Result: result}, nil
}

func (s *audioManagerServer) GetActivePlaybackConfigurations(_ context.Context, req *pb.GetActivePlaybackConfigurationsRequest) (*pb.GetActivePlaybackConfigurationsResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetActivePlaybackConfigurations()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetActivePlaybackConfigurationsResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetActiveRecordingConfigurations(_ context.Context, req *pb.GetActiveRecordingConfigurationsRequest) (*pb.GetActiveRecordingConfigurationsResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetActiveRecordingConfigurations()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetActiveRecordingConfigurationsResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetAllowedCapturePolicy(_ context.Context, req *pb.GetAllowedCapturePolicyRequest) (*pb.GetAllowedCapturePolicyResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAllowedCapturePolicy()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetAllowedCapturePolicyResponse{Result: result}, nil
}

func (s *audioManagerServer) GetAudioDevicesForAttributes(_ context.Context, req *pb.GetAudioDevicesForAttributesRequest) (*pb.GetAudioDevicesForAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAudioDevicesForAttributes(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetAudioDevicesForAttributesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetAudioHwSyncForSession(_ context.Context, req *pb.GetAudioHwSyncForSessionRequest) (*pb.GetAudioHwSyncForSessionResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAudioHwSyncForSession(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetAudioHwSyncForSessionResponse{Result: result}, nil
}

func (s *audioManagerServer) GetAvailableCommunicationDevices(_ context.Context, req *pb.GetAvailableCommunicationDevicesRequest) (*pb.GetAvailableCommunicationDevicesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAvailableCommunicationDevices()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetAvailableCommunicationDevicesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetCommunicationDevice(_ context.Context, req *pb.GetCommunicationDeviceRequest) (*pb.GetCommunicationDeviceResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetCommunicationDevice()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetCommunicationDeviceResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetDevices(_ context.Context, req *pb.GetDevicesRequest) (*pb.GetDevicesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetDevices(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetDevicesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetDirectProfilesForAttributes(_ context.Context, req *pb.GetDirectProfilesForAttributesRequest) (*pb.GetDirectProfilesForAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetDirectProfilesForAttributes(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetDirectProfilesForAttributesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetEncodedSurroundMode(_ context.Context, req *pb.GetEncodedSurroundModeRequest) (*pb.GetEncodedSurroundModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetEncodedSurroundMode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetEncodedSurroundModeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetMicrophones(_ context.Context, req *pb.GetMicrophonesRequest) (*pb.GetMicrophonesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetMicrophones()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetMicrophonesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetMode(_ context.Context, req *pb.GetModeRequest) (*pb.GetModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetMode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetModeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetParameters(_ context.Context, req *pb.GetParametersRequest) (*pb.GetParametersResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetParameters(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetParametersResponse{Result: result}, nil
}

func (s *audioManagerServer) GetPreferredMixerAttributes(_ context.Context, req *pb.GetPreferredMixerAttributesRequest) (*pb.GetPreferredMixerAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetPreferredMixerAttributes(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetPreferredMixerAttributesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetProperty(_ context.Context, req *pb.GetPropertyRequest) (*pb.GetPropertyResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetProperty(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetPropertyResponse{Result: result}, nil
}

func (s *audioManagerServer) GetRingerMode(_ context.Context, req *pb.GetRingerModeRequest) (*pb.GetRingerModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetRingerMode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetRingerModeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetRouting(_ context.Context, req *pb.GetRoutingRequest) (*pb.GetRoutingResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetRouting(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetRoutingResponse{Result: result}, nil
}

func (s *audioManagerServer) GetSpatializer(_ context.Context, req *pb.GetSpatializerRequest) (*pb.GetSpatializerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetSpatializer()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetSpatializerResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetStreamMaxVolume(_ context.Context, req *pb.GetStreamMaxVolumeRequest) (*pb.GetStreamMaxVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetStreamMaxVolume(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetStreamMaxVolumeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetStreamMinVolume(_ context.Context, req *pb.GetStreamMinVolumeRequest) (*pb.GetStreamMinVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetStreamMinVolume(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetStreamMinVolumeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetStreamVolume(_ context.Context, req *pb.GetStreamVolumeRequest) (*pb.GetStreamVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetStreamVolume(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetStreamVolumeResponse{Result: result}, nil
}

func (s *audioManagerServer) GetStreamVolumeDb(_ context.Context, req *pb.GetStreamVolumeDbRequest) (*pb.GetStreamVolumeDbResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetStreamVolumeDb(req.GetArg0(), req.GetArg1(), req.GetArg2())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetStreamVolumeDbResponse{Result: result}, nil
}

func (s *audioManagerServer) GetSupportedDeviceTypes(_ context.Context, req *pb.GetSupportedDeviceTypesRequest) (*pb.GetSupportedDeviceTypesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetSupportedDeviceTypes(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetSupportedDeviceTypesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetSupportedMixerAttributes(_ context.Context, req *pb.GetSupportedMixerAttributesRequest) (*pb.GetSupportedMixerAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetSupportedMixerAttributes(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetSupportedMixerAttributesResponse{Result: handle}, nil
}

func (s *audioManagerServer) GetVibrateSetting(_ context.Context, req *pb.GetVibrateSettingRequest) (*pb.GetVibrateSettingResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetVibrateSetting(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetVibrateSettingResponse{Result: result}, nil
}

func (s *audioManagerServer) GetVolumeGroupIdForAttributes(_ context.Context, req *pb.GetVolumeGroupIdForAttributesRequest) (*pb.GetVolumeGroupIdForAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetVolumeGroupIdForAttributes(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetVolumeGroupIdForAttributesResponse{Result: result}, nil
}

func (s *audioManagerServer) IsBluetoothA2DpOn(_ context.Context, req *pb.IsBluetoothA2DpOnRequest) (*pb.IsBluetoothA2DpOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsBluetoothA2dpOn()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsBluetoothA2DpOnResponse{Result: result}, nil
}

func (s *audioManagerServer) IsBluetoothScoAvailableOffCall(_ context.Context, req *pb.IsBluetoothScoAvailableOffCallRequest) (*pb.IsBluetoothScoAvailableOffCallResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsBluetoothScoAvailableOffCall()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsBluetoothScoAvailableOffCallResponse{Result: result}, nil
}

func (s *audioManagerServer) IsBluetoothScoOn(_ context.Context, req *pb.IsBluetoothScoOnRequest) (*pb.IsBluetoothScoOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsBluetoothScoOn()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsBluetoothScoOnResponse{Result: result}, nil
}

func (s *audioManagerServer) IsCallScreeningModeSupported(_ context.Context, req *pb.IsCallScreeningModeSupportedRequest) (*pb.IsCallScreeningModeSupportedResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsCallScreeningModeSupported()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsCallScreeningModeSupportedResponse{Result: result}, nil
}

func (s *audioManagerServer) IsMicrophoneMute(_ context.Context, req *pb.IsMicrophoneMuteRequest) (*pb.IsMicrophoneMuteResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsMicrophoneMute()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsMicrophoneMuteResponse{Result: result}, nil
}

func (s *audioManagerServer) IsMusicActive(_ context.Context, req *pb.IsMusicActiveRequest) (*pb.IsMusicActiveResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsMusicActive()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsMusicActiveResponse{Result: result}, nil
}

func (s *audioManagerServer) IsRampingRingerEnabled(_ context.Context, req *pb.IsRampingRingerEnabledRequest) (*pb.IsRampingRingerEnabledResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsRampingRingerEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsRampingRingerEnabledResponse{Result: result}, nil
}

func (s *audioManagerServer) IsSpeakerphoneOn(_ context.Context, req *pb.IsSpeakerphoneOnRequest) (*pb.IsSpeakerphoneOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsSpeakerphoneOn()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsSpeakerphoneOnResponse{Result: result}, nil
}

func (s *audioManagerServer) IsStreamMute(_ context.Context, req *pb.IsStreamMuteRequest) (*pb.IsStreamMuteResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsStreamMute(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsStreamMuteResponse{Result: result}, nil
}

func (s *audioManagerServer) IsSurroundFormatEnabled(_ context.Context, req *pb.IsSurroundFormatEnabledRequest) (*pb.IsSurroundFormatEnabledResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsSurroundFormatEnabled(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsSurroundFormatEnabledResponse{Result: result}, nil
}

func (s *audioManagerServer) IsVolumeFixed(_ context.Context, req *pb.IsVolumeFixedRequest) (*pb.IsVolumeFixedResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsVolumeFixed()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsVolumeFixedResponse{Result: result}, nil
}

func (s *audioManagerServer) IsVolumeGroupMuted(_ context.Context, req *pb.IsVolumeGroupMutedRequest) (*pb.IsVolumeGroupMutedResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsVolumeGroupMuted(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsVolumeGroupMutedResponse{Result: result}, nil
}

func (s *audioManagerServer) IsWiredHeadsetOn(_ context.Context, req *pb.IsWiredHeadsetOnRequest) (*pb.IsWiredHeadsetOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsWiredHeadsetOn()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsWiredHeadsetOnResponse{Result: result}, nil
}

func (s *audioManagerServer) LoadSoundEffects(_ context.Context, req *pb.LoadSoundEffectsRequest) (*pb.LoadSoundEffectsResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.LoadSoundEffects(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.LoadSoundEffectsResponse{}, nil
}

func (s *audioManagerServer) PlaySoundEffect1(_ context.Context, req *pb.PlaySoundEffect1Request) (*pb.PlaySoundEffect1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.PlaySoundEffect1(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.PlaySoundEffect1Response{}, nil
}

func (s *audioManagerServer) PlaySoundEffect2_1(_ context.Context, req *pb.PlaySoundEffect2_1Request) (*pb.PlaySoundEffect2_1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.PlaySoundEffect2_1(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.PlaySoundEffect2_1Response{}, nil
}

func (s *audioManagerServer) RegisterMediaButtonEventReceiver1(_ context.Context, req *pb.RegisterMediaButtonEventReceiver1Request) (*pb.RegisterMediaButtonEventReceiver1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterMediaButtonEventReceiver1(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterMediaButtonEventReceiver1Response{}, nil
}

func (s *audioManagerServer) RegisterMediaButtonEventReceiver1_1(_ context.Context, req *pb.RegisterMediaButtonEventReceiver1_1Request) (*pb.RegisterMediaButtonEventReceiver1_1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterMediaButtonEventReceiver1_1(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterMediaButtonEventReceiver1_1Response{}, nil
}

func (s *audioManagerServer) RegisterRemoteControlClient(_ context.Context, req *pb.RegisterRemoteControlClientRequest) (*pb.RegisterRemoteControlClientResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterRemoteControlClient(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterRemoteControlClientResponse{}, nil
}

func (s *audioManagerServer) RegisterRemoteController(_ context.Context, req *pb.RegisterRemoteControllerRequest) (*pb.RegisterRemoteControllerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.RegisterRemoteController(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterRemoteControllerResponse{Result: result}, nil
}

func (s *audioManagerServer) RemoveOnCommunicationDeviceChangedListener(_ context.Context, req *pb.RemoveOnCommunicationDeviceChangedListenerRequest) (*pb.RemoveOnCommunicationDeviceChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RemoveOnCommunicationDeviceChangedListener(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RemoveOnCommunicationDeviceChangedListenerResponse{}, nil
}

func (s *audioManagerServer) RemoveOnModeChangedListener(_ context.Context, req *pb.RemoveOnModeChangedListenerRequest) (*pb.RemoveOnModeChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RemoveOnModeChangedListener(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RemoveOnModeChangedListenerResponse{}, nil
}

func (s *audioManagerServer) RemoveOnPreferredMixerAttributesChangedListener(_ context.Context, req *pb.RemoveOnPreferredMixerAttributesChangedListenerRequest) (*pb.RemoveOnPreferredMixerAttributesChangedListenerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RemoveOnPreferredMixerAttributesChangedListener(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RemoveOnPreferredMixerAttributesChangedListenerResponse{}, nil
}

func (s *audioManagerServer) RequestAudioFocus1(_ context.Context, req *pb.RequestAudioFocus1Request) (*pb.RequestAudioFocus1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.RequestAudioFocus1(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RequestAudioFocus1Response{Result: result}, nil
}

func (s *audioManagerServer) RequestAudioFocus3_1(_ context.Context, req *pb.RequestAudioFocus3_1Request) (*pb.RequestAudioFocus3_1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.RequestAudioFocus3_1(s.Handles.Get(req.GetArg0()), req.GetArg1(), req.GetArg2())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RequestAudioFocus3_1Response{Result: result}, nil
}

func (s *audioManagerServer) SetAllowedCapturePolicy(_ context.Context, req *pb.SetAllowedCapturePolicyRequest) (*pb.SetAllowedCapturePolicyResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetAllowedCapturePolicy(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetAllowedCapturePolicyResponse{}, nil
}

func (s *audioManagerServer) SetBluetoothA2DpOn(_ context.Context, req *pb.SetBluetoothA2DpOnRequest) (*pb.SetBluetoothA2DpOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetBluetoothA2dpOn(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetBluetoothA2DpOnResponse{}, nil
}

func (s *audioManagerServer) SetBluetoothScoOn(_ context.Context, req *pb.SetBluetoothScoOnRequest) (*pb.SetBluetoothScoOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetBluetoothScoOn(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetBluetoothScoOnResponse{}, nil
}

func (s *audioManagerServer) SetCommunicationDevice(_ context.Context, req *pb.SetCommunicationDeviceRequest) (*pb.SetCommunicationDeviceResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.SetCommunicationDevice(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetCommunicationDeviceResponse{Result: result}, nil
}

func (s *audioManagerServer) SetEncodedSurroundMode(_ context.Context, req *pb.SetEncodedSurroundModeRequest) (*pb.SetEncodedSurroundModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.SetEncodedSurroundMode(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetEncodedSurroundModeResponse{Result: result}, nil
}

func (s *audioManagerServer) SetMicrophoneMute(_ context.Context, req *pb.SetMicrophoneMuteRequest) (*pb.SetMicrophoneMuteResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetMicrophoneMute(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetMicrophoneMuteResponse{}, nil
}

func (s *audioManagerServer) SetMode(_ context.Context, req *pb.SetModeRequest) (*pb.SetModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetMode(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetModeResponse{}, nil
}

func (s *audioManagerServer) SetParameters(_ context.Context, req *pb.SetParametersRequest) (*pb.SetParametersResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetParameters(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetParametersResponse{}, nil
}

func (s *audioManagerServer) SetPreferredMixerAttributes(_ context.Context, req *pb.SetPreferredMixerAttributesRequest) (*pb.SetPreferredMixerAttributesResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.SetPreferredMixerAttributes(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()), s.Handles.Get(req.GetArg2()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetPreferredMixerAttributesResponse{Result: result}, nil
}

func (s *audioManagerServer) SetRingerMode(_ context.Context, req *pb.SetRingerModeRequest) (*pb.SetRingerModeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetRingerMode(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetRingerModeResponse{}, nil
}

func (s *audioManagerServer) SetRouting(_ context.Context, req *pb.SetRoutingRequest) (*pb.SetRoutingResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetRouting(req.GetArg0(), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetRoutingResponse{}, nil
}

func (s *audioManagerServer) SetSpeakerphoneOn(_ context.Context, req *pb.SetSpeakerphoneOnRequest) (*pb.SetSpeakerphoneOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetSpeakerphoneOn(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetSpeakerphoneOnResponse{}, nil
}

func (s *audioManagerServer) SetStreamMute(_ context.Context, req *pb.SetStreamMuteRequest) (*pb.SetStreamMuteResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetStreamMute(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetStreamMuteResponse{}, nil
}

func (s *audioManagerServer) SetStreamSolo(_ context.Context, req *pb.SetStreamSoloRequest) (*pb.SetStreamSoloResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetStreamSolo(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetStreamSoloResponse{}, nil
}

func (s *audioManagerServer) SetStreamVolume(_ context.Context, req *pb.SetStreamVolumeRequest) (*pb.SetStreamVolumeResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetStreamVolume(req.GetArg0(), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetStreamVolumeResponse{}, nil
}

func (s *audioManagerServer) SetSurroundFormatEnabled(_ context.Context, req *pb.SetSurroundFormatEnabledRequest) (*pb.SetSurroundFormatEnabledResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.SetSurroundFormatEnabled(req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetSurroundFormatEnabledResponse{Result: result}, nil
}

func (s *audioManagerServer) SetVibrateSetting(_ context.Context, req *pb.SetVibrateSettingRequest) (*pb.SetVibrateSettingResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetVibrateSetting(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetVibrateSettingResponse{}, nil
}

func (s *audioManagerServer) SetWiredHeadsetOn(_ context.Context, req *pb.SetWiredHeadsetOnRequest) (*pb.SetWiredHeadsetOnResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetWiredHeadsetOn(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetWiredHeadsetOnResponse{}, nil
}

func (s *audioManagerServer) ShouldVibrate(_ context.Context, req *pb.ShouldVibrateRequest) (*pb.ShouldVibrateResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.ShouldVibrate(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ShouldVibrateResponse{Result: result}, nil
}

func (s *audioManagerServer) StartBluetoothSco(_ context.Context, req *pb.StartBluetoothScoRequest) (*pb.StartBluetoothScoResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.StartBluetoothSco(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.StartBluetoothScoResponse{}, nil
}

func (s *audioManagerServer) StopBluetoothSco(_ context.Context, req *pb.StopBluetoothScoRequest) (*pb.StopBluetoothScoResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.StopBluetoothSco(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.StopBluetoothScoResponse{}, nil
}

func (s *audioManagerServer) UnloadSoundEffects(_ context.Context, req *pb.UnloadSoundEffectsRequest) (*pb.UnloadSoundEffectsResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnloadSoundEffects(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnloadSoundEffectsResponse{}, nil
}

func (s *audioManagerServer) UnregisterAudioDeviceCallback(_ context.Context, req *pb.UnregisterAudioDeviceCallbackRequest) (*pb.UnregisterAudioDeviceCallbackResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterAudioDeviceCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterAudioDeviceCallbackResponse{}, nil
}

func (s *audioManagerServer) UnregisterAudioPlaybackCallback(_ context.Context, req *pb.UnregisterAudioPlaybackCallbackRequest) (*pb.UnregisterAudioPlaybackCallbackResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterAudioPlaybackCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterAudioPlaybackCallbackResponse{}, nil
}

func (s *audioManagerServer) UnregisterAudioRecordingCallback(_ context.Context, req *pb.UnregisterAudioRecordingCallbackRequest) (*pb.UnregisterAudioRecordingCallbackResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterAudioRecordingCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterAudioRecordingCallbackResponse{}, nil
}

func (s *audioManagerServer) UnregisterMediaButtonEventReceiver1(_ context.Context, req *pb.UnregisterMediaButtonEventReceiver1Request) (*pb.UnregisterMediaButtonEventReceiver1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterMediaButtonEventReceiver1(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterMediaButtonEventReceiver1Response{}, nil
}

func (s *audioManagerServer) UnregisterMediaButtonEventReceiver1_1(_ context.Context, req *pb.UnregisterMediaButtonEventReceiver1_1Request) (*pb.UnregisterMediaButtonEventReceiver1_1Response, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterMediaButtonEventReceiver1_1(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterMediaButtonEventReceiver1_1Response{}, nil
}

func (s *audioManagerServer) UnregisterRemoteControlClient(_ context.Context, req *pb.UnregisterRemoteControlClientRequest) (*pb.UnregisterRemoteControlClientResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterRemoteControlClient(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterRemoteControlClientResponse{}, nil
}

func (s *audioManagerServer) UnregisterRemoteController(_ context.Context, req *pb.UnregisterRemoteControllerRequest) (*pb.UnregisterRemoteControllerResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterRemoteController(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterRemoteControllerResponse{}, nil
}

func (s *audioManagerServer) GetDirectPlaybackSupport(_ context.Context, req *pb.GetDirectPlaybackSupportRequest) (*pb.GetDirectPlaybackSupportResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetDirectPlaybackSupport(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetDirectPlaybackSupportResponse{Result: result}, nil
}

func (s *audioManagerServer) GetPlaybackOffloadSupport(_ context.Context, req *pb.GetPlaybackOffloadSupportRequest) (*pb.GetPlaybackOffloadSupportResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetPlaybackOffloadSupport(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetPlaybackOffloadSupportResponse{Result: result}, nil
}

func (s *audioManagerServer) IsHapticPlaybackSupported(_ context.Context, req *pb.IsHapticPlaybackSupportedRequest) (*pb.IsHapticPlaybackSupportedResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsHapticPlaybackSupported()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsHapticPlaybackSupportedResponse{Result: result}, nil
}

func (s *audioManagerServer) IsOffloadedPlaybackSupported(_ context.Context, req *pb.IsOffloadedPlaybackSupportedRequest) (*pb.IsOffloadedPlaybackSupportedResponse, error) {
	mgr, err := jnipkg.NewaudioManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsOffloadedPlaybackSupported(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsOffloadedPlaybackSupportedResponse{Result: result}, nil
}
