// Code generated by javagen. DO NOT EDIT.

package print

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/xaionaro-go/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	initOnce sync.Once
	initErr  error

	clsprintJobInfo                        *jni.GlobalRef
	midprintJobInfoDescribeContents        jni.MethodID
	midprintJobInfoGetAdvancedIntOption    jni.MethodID
	midprintJobInfoGetAdvancedStringOption jni.MethodID
	midprintJobInfoGetAttributes           jni.MethodID
	midprintJobInfoGetCopies               jni.MethodID
	midprintJobInfoGetCreationTime         jni.MethodID
	midprintJobInfoGetId                   jni.MethodID
	midprintJobInfoGetLabel                jni.MethodID
	midprintJobInfoGetPages                jni.MethodID
	midprintJobInfoGetPrinterId            jni.MethodID
	midprintJobInfoGetState                jni.MethodID
	midprintJobInfoHasAdvancedOption       jni.MethodID
	midprintJobInfoToString                jni.MethodID
	midprintJobInfoWriteToParcel           jni.MethodID
)

// initSkipped records methods that were not found during init.
// These are typically methods that do not exist on the current device's
// Android API level. Calls to such methods will return an error at
// invocation time instead of preventing the entire service from loading.
var initSkipped []string

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("android/print/PrintJobInfo")
	if err != nil {
		return fmt.Errorf("find class android.print.PrintJobInfo: %w", err)
	}
	clsprintJobInfo = env.NewGlobalRef(&c.Object)

	midprintJobInfoDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.describeContents")
	}

	midprintJobInfoGetAdvancedIntOption, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getAdvancedIntOption", "(Ljava/lang/String;)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getAdvancedIntOption")
	}

	midprintJobInfoGetAdvancedStringOption, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getAdvancedStringOption", "(Ljava/lang/String;)Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getAdvancedStringOption")
	}

	midprintJobInfoGetAttributes, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getAttributes", "()Landroid/print/PrintAttributes;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getAttributes")
	}

	midprintJobInfoGetCopies, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getCopies", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getCopies")
	}

	midprintJobInfoGetCreationTime, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getCreationTime", "()J")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getCreationTime")
	}

	midprintJobInfoGetId, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getId", "()Landroid/print/PrintJobId;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getId")
	}

	midprintJobInfoGetLabel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getLabel", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getLabel")
	}

	midprintJobInfoGetPages, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getPages", "()[Landroid/print/PageRange;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getPages")
	}

	midprintJobInfoGetPrinterId, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getPrinterId", "()Landroid/print/PrinterId;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getPrinterId")
	}

	midprintJobInfoGetState, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "getState", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.getState")
	}

	midprintJobInfoHasAdvancedOption, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "hasAdvancedOption", "(Ljava/lang/String;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.hasAdvancedOption")
	}

	midprintJobInfoToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "toString", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.toString")
	}

	midprintJobInfoWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsprintJobInfo)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.print.PrintJobInfo.writeToParcel")
	}

	return nil
}
