EXAMPLE_NAME        := iot_gateway
EXAMPLE_PERMISSIONS := android.permission.BLUETOOTH_CONNECT android.permission.BLUETOOTH_SCAN android.permission.ACCESS_WIFI_STATE android.permission.NFC

include ../apk.mk
