// Code generated by javagen. DO NOT EDIT.

package download

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Query wraps android.app.DownloadManager$Query.
type Query struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// SetFilterById calls android.app.DownloadManager$Query.setFilterById.
func (m *Query) SetFilterById(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midQuerySetFilterById == nil {
			callErr = fmt.Errorf("android.app.DownloadManager$Query.setFilterById is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midQuerySetFilterById, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// SetFilterByStatus calls android.app.DownloadManager$Query.setFilterByStatus.
func (m *Query) SetFilterByStatus(arg0 int32) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midQuerySetFilterByStatus == nil {
			callErr = fmt.Errorf("android.app.DownloadManager$Query.setFilterByStatus is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midQuerySetFilterByStatus, jni.IntValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
