EXAMPLE_NAME        := device_health_dashboard
EXAMPLE_PERMISSIONS := android.permission.ACCESS_WIFI_STATE android.permission.ACCESS_NETWORK_STATE android.permission.READ_PHONE_STATE

include ../apk.mk
