// Code generated by javagen. DO NOT EDIT.

package nsd

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	initOnce sync.Once
	initErr  error

	clsManager                              *jni.GlobalRef
	midManagerDiscoverServices3             jni.MethodID
	midManagerDiscoverServices5_1           jni.MethodID
	midManagerDiscoverServices5_2           jni.MethodID
	midManagerDiscoverServices3_3           jni.MethodID
	midManagerRegisterService3              jni.MethodID
	midManagerRegisterService4_1            jni.MethodID
	midManagerRegisterServiceInfoCallback   jni.MethodID
	midManagerResolveService2               jni.MethodID
	midManagerResolveService3_1             jni.MethodID
	midManagerStopServiceDiscovery          jni.MethodID
	midManagerStopServiceResolution         jni.MethodID
	midManagerUnregisterService             jni.MethodID
	midManagerUnregisterServiceInfoCallback jni.MethodID

	clsServiceInfo                 *jni.GlobalRef
	midServiceInfoDescribeContents jni.MethodID
	midServiceInfoGetHost          jni.MethodID
	midServiceInfoGetHostAddresses jni.MethodID
	midServiceInfoGetHostname      jni.MethodID
	midServiceInfoGetNetwork       jni.MethodID
	midServiceInfoGetPort          jni.MethodID
	midServiceInfoGetServiceName   jni.MethodID
	midServiceInfoGetServiceType   jni.MethodID
	midServiceInfoGetSubtypes      jni.MethodID
	midServiceInfoRemoveAttribute  jni.MethodID
	midServiceInfoSetAttribute     jni.MethodID
	midServiceInfoSetHost          jni.MethodID
	midServiceInfoSetHostAddresses jni.MethodID
	midServiceInfoSetNetwork       jni.MethodID
	midServiceInfoSetPort          jni.MethodID
	midServiceInfoSetServiceName   jni.MethodID
	midServiceInfoSetServiceType   jni.MethodID
	midServiceInfoSetSubtypes      jni.MethodID
	midServiceInfoToString         jni.MethodID
	midServiceInfoWriteToParcel    jni.MethodID
)

// initSkipped records methods that were not found during init.
// These are typically methods that do not exist on the current device's
// Android API level. Calls to such methods will return an error at
// invocation time instead of preventing the entire service from loading.
var initSkipped []string

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("android/net/nsd/NsdManager")
	if err != nil {
		return fmt.Errorf("find class android.net.nsd.NsdManager: %w", err)
	}
	clsManager = env.NewGlobalRef(&c.Object)

	midManagerDiscoverServices3, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "discoverServices", "(Landroid/net/nsd/DiscoveryRequest;Ljava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$DiscoveryListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.discoverServices")
	}

	midManagerDiscoverServices5_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "discoverServices", "(Ljava/lang/String;ILandroid/net/Network;Ljava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$DiscoveryListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.discoverServices")
	}

	midManagerDiscoverServices5_2, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "discoverServices", "(Ljava/lang/String;ILandroid/net/NetworkRequest;Ljava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$DiscoveryListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.discoverServices")
	}

	midManagerDiscoverServices3_3, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "discoverServices", "(Ljava/lang/String;ILandroid/net/nsd/NsdManager$DiscoveryListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.discoverServices")
	}

	midManagerRegisterService3, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "registerService", "(Landroid/net/nsd/NsdServiceInfo;ILandroid/net/nsd/NsdManager$RegistrationListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.registerService")
	}

	midManagerRegisterService4_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "registerService", "(Landroid/net/nsd/NsdServiceInfo;ILjava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$RegistrationListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.registerService")
	}

	midManagerRegisterServiceInfoCallback, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "registerServiceInfoCallback", "(Landroid/net/nsd/NsdServiceInfo;Ljava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$ServiceInfoCallback;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.registerServiceInfoCallback")
	}

	midManagerResolveService2, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "resolveService", "(Landroid/net/nsd/NsdServiceInfo;Landroid/net/nsd/NsdManager$ResolveListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.resolveService")
	}

	midManagerResolveService3_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "resolveService", "(Landroid/net/nsd/NsdServiceInfo;Ljava/util/concurrent/Executor;Landroid/net/nsd/NsdManager$ResolveListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.resolveService")
	}

	midManagerStopServiceDiscovery, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "stopServiceDiscovery", "(Landroid/net/nsd/NsdManager$DiscoveryListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.stopServiceDiscovery")
	}

	midManagerStopServiceResolution, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "stopServiceResolution", "(Landroid/net/nsd/NsdManager$ResolveListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.stopServiceResolution")
	}

	midManagerUnregisterService, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "unregisterService", "(Landroid/net/nsd/NsdManager$RegistrationListener;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.unregisterService")
	}

	midManagerUnregisterServiceInfoCallback, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "unregisterServiceInfoCallback", "(Landroid/net/nsd/NsdManager$ServiceInfoCallback;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdManager.unregisterServiceInfoCallback")
	}

	c, err = env.FindClass("android/net/nsd/NsdServiceInfo")
	if err != nil {
		return fmt.Errorf("find class android.net.nsd.NsdServiceInfo: %w", err)
	}
	clsServiceInfo = env.NewGlobalRef(&c.Object)

	midServiceInfoDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.describeContents")
	}

	midServiceInfoGetHost, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getHost", "()Ljava/net/InetAddress;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getHost")
	}

	midServiceInfoGetHostAddresses, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getHostAddresses", "()Ljava/util/List;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getHostAddresses")
	}

	midServiceInfoGetHostname, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getHostname", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getHostname")
	}

	midServiceInfoGetNetwork, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getNetwork", "()Landroid/net/Network;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getNetwork")
	}

	midServiceInfoGetPort, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getPort", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getPort")
	}

	midServiceInfoGetServiceName, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getServiceName", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getServiceName")
	}

	midServiceInfoGetServiceType, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getServiceType", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getServiceType")
	}

	midServiceInfoGetSubtypes, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "getSubtypes", "()Ljava/util/Set;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.getSubtypes")
	}

	midServiceInfoRemoveAttribute, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "removeAttribute", "(Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.removeAttribute")
	}

	midServiceInfoSetAttribute, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setAttribute", "(Ljava/lang/String;Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setAttribute")
	}

	midServiceInfoSetHost, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setHost", "(Ljava/net/InetAddress;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setHost")
	}

	midServiceInfoSetHostAddresses, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setHostAddresses", "(Ljava/util/List;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setHostAddresses")
	}

	midServiceInfoSetNetwork, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setNetwork", "(Landroid/net/Network;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setNetwork")
	}

	midServiceInfoSetPort, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setPort", "(I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setPort")
	}

	midServiceInfoSetServiceName, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setServiceName", "(Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setServiceName")
	}

	midServiceInfoSetServiceType, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setServiceType", "(Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setServiceType")
	}

	midServiceInfoSetSubtypes, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "setSubtypes", "(Ljava/util/Set;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.setSubtypes")
	}

	midServiceInfoToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "toString", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.toString")
	}

	midServiceInfoWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsServiceInfo)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.net.nsd.NsdServiceInfo.writeToParcel")
	}

	return nil
}
