// Code generated by javagen. DO NOT EDIT.

package credentials

import "github.com/AndroidGoLab/jni/credentials/consts"

const (
	Creator = consts.Creator
)

const (
	TypeUnknown            = consts.TypeUnknown
	SupportedElementKeys   = consts.SupportedElementKeys
	TypeInterrupted        = consts.TypeInterrupted
	TypeNoCreateOptions    = consts.TypeNoCreateOptions
	TypeUserCanceled       = consts.TypeUserCanceled
	TypeNoCredential       = consts.TypeNoCredential
	TypePasswordCredential = consts.TypePasswordCredential
)
