// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DeniedByServerException wraps android.media.DeniedByServerException.
type DeniedByServerException struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewDeniedByServerException creates a new android.media.DeniedByServerException instance.
func NewDeniedByServerException(vm *jni.VM, arg0 string) (*DeniedByServerException, error) {
	var t DeniedByServerException
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsDeniedByServerException)), midDeniedByServerExceptionCtor, jni.ObjectValue(&jArg0.Object))
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}
