// Code generated by javagen. DO NOT EDIT.

package media

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// RouterVolumeCallback wraps android.media.MediaRouter$VolumeCallback.
type RouterVolumeCallback struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnVolumeSetRequest calls android.media.MediaRouter$VolumeCallback.onVolumeSetRequest.
func (m *RouterVolumeCallback) OnVolumeSetRequest(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRouterVolumeCallbackOnVolumeSetRequest == nil {
			callErr = fmt.Errorf("android.media.MediaRouter$VolumeCallback.onVolumeSetRequest is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRouterVolumeCallbackOnVolumeSetRequest, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// OnVolumeUpdateRequest calls android.media.MediaRouter$VolumeCallback.onVolumeUpdateRequest.
func (m *RouterVolumeCallback) OnVolumeUpdateRequest(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRouterVolumeCallbackOnVolumeUpdateRequest == nil {
			callErr = fmt.Errorf("android.media.MediaRouter$VolumeCallback.onVolumeUpdateRequest is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRouterVolumeCallbackOnVolumeUpdateRequest, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
