EXAMPLE_NAME        := wifi_direct_transfer
EXAMPLE_PERMISSIONS := android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_WIFI_STATE android.permission.CHANGE_WIFI_STATE android.permission.NEARBY_WIFI_DEVICES

include ../apk.mk
