// Code generated by javagen. DO NOT EDIT.

package ims

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ProvisioningManagerFeatureProvisioningCallback wraps android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback.
type ProvisioningManagerFeatureProvisioningCallback struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnFeatureProvisioningChanged calls android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback.onFeatureProvisioningChanged.
func (m *ProvisioningManagerFeatureProvisioningCallback) OnFeatureProvisioningChanged(
	arg0 int32,
	arg1 int32,
	arg2 bool,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProvisioningManagerFeatureProvisioningCallbackOnFeatureProvisioningChanged == nil {
			callErr = fmt.Errorf("android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback.onFeatureProvisioningChanged is not available on this device")
			return callErr
		}

		var jArg2 uint8
		if arg2 {
			jArg2 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midProvisioningManagerFeatureProvisioningCallbackOnFeatureProvisioningChanged, jni.IntValue(arg0), jni.IntValue(arg1), jni.BooleanValue(jArg2),
		)
		return callErr
	})
	return callErr
}

// OnRcsFeatureProvisioningChanged calls android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback.onRcsFeatureProvisioningChanged.
func (m *ProvisioningManagerFeatureProvisioningCallback) OnRcsFeatureProvisioningChanged(
	arg0 int32,
	arg1 int32,
	arg2 bool,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProvisioningManagerFeatureProvisioningCallbackOnRcsFeatureProvisioningChanged == nil {
			callErr = fmt.Errorf("android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback.onRcsFeatureProvisioningChanged is not available on this device")
			return callErr
		}

		var jArg2 uint8
		if arg2 {
			jArg2 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midProvisioningManagerFeatureProvisioningCallbackOnRcsFeatureProvisioningChanged, jni.IntValue(arg0), jni.IntValue(arg1), jni.BooleanValue(jArg2),
		)
		return callErr
	})
	return callErr
}
