// Code generated by javagen. DO NOT EDIT.

package tv

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// InputServiceRecordingSession wraps android.media.tv.TvInputService$RecordingSession.
type InputServiceRecordingSession struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NotifyError calls android.media.tv.TvInputService$RecordingSession.notifyError.
func (m *InputServiceRecordingSession) NotifyError(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionNotifyError == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.notifyError is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionNotifyError, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// NotifyRecordingStopped calls android.media.tv.TvInputService$RecordingSession.notifyRecordingStopped.
func (m *InputServiceRecordingSession) NotifyRecordingStopped(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionNotifyRecordingStopped == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.notifyRecordingStopped is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionNotifyRecordingStopped, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// NotifyTuned calls android.media.tv.TvInputService$RecordingSession.notifyTuned.
func (m *InputServiceRecordingSession) NotifyTuned(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionNotifyTuned == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.notifyTuned is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionNotifyTuned, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnAppPrivateCommand calls android.media.tv.TvInputService$RecordingSession.onAppPrivateCommand.
func (m *InputServiceRecordingSession) OnAppPrivateCommand(arg0 string, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnAppPrivateCommand == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onAppPrivateCommand is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnAppPrivateCommand, jni.ObjectValue(&jArg0.Object), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// OnPauseRecording calls android.media.tv.TvInputService$RecordingSession.onPauseRecording.
func (m *InputServiceRecordingSession) OnPauseRecording(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnPauseRecording == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onPauseRecording is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnPauseRecording, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnRelease calls android.media.tv.TvInputService$RecordingSession.onRelease.
func (m *InputServiceRecordingSession) OnRelease() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnRelease == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onRelease is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnRelease,
		)
		return callErr
	})
	return callErr
}

// OnResumeRecording calls android.media.tv.TvInputService$RecordingSession.onResumeRecording.
func (m *InputServiceRecordingSession) OnResumeRecording(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnResumeRecording == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onResumeRecording is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnResumeRecording, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnStartRecording1 calls android.media.tv.TvInputService$RecordingSession.onStartRecording.
func (m *InputServiceRecordingSession) OnStartRecording1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnStartRecording1 == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onStartRecording is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnStartRecording1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnStartRecording2_1 calls android.media.tv.TvInputService$RecordingSession.onStartRecording.
func (m *InputServiceRecordingSession) OnStartRecording2_1(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnStartRecording2_1 == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onStartRecording is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnStartRecording2_1, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// OnStopRecording calls android.media.tv.TvInputService$RecordingSession.onStopRecording.
func (m *InputServiceRecordingSession) OnStopRecording() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnStopRecording == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onStopRecording is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnStopRecording,
		)
		return callErr
	})
	return callErr
}

// OnTune1 calls android.media.tv.TvInputService$RecordingSession.onTune.
func (m *InputServiceRecordingSession) OnTune1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnTune1 == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onTune is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnTune1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnTune2_1 calls android.media.tv.TvInputService$RecordingSession.onTune.
func (m *InputServiceRecordingSession) OnTune2_1(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midInputServiceRecordingSessionOnTune2_1 == nil {
			callErr = fmt.Errorf("android.media.tv.TvInputService$RecordingSession.onTune is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midInputServiceRecordingSessionOnTune2_1, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}
