// Code generated by javagen. DO NOT EDIT.

package tv

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PesResponse wraps android.media.tv.PesResponse.
type PesResponse struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// DescribeContents calls android.media.tv.PesResponse.describeContents.
func (m *PesResponse) DescribeContents() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPesResponseDescribeContents == nil {
			callErr = fmt.Errorf("android.media.tv.PesResponse.describeContents is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midPesResponseDescribeContents,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSharedFilterToken calls android.media.tv.PesResponse.getSharedFilterToken.
func (m *PesResponse) GetSharedFilterToken() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPesResponseGetSharedFilterToken == nil {
			callErr = fmt.Errorf("android.media.tv.PesResponse.getSharedFilterToken is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midPesResponseGetSharedFilterToken,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// WriteToParcel calls android.media.tv.PesResponse.writeToParcel.
func (m *PesResponse) WriteToParcel(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPesResponseWriteToParcel == nil {
			callErr = fmt.Errorf("android.media.tv.PesResponse.writeToParcel is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPesResponseWriteToParcel, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}
