EXAMPLE_NAME        := bt_gatt_client
EXAMPLE_PERMISSIONS := android.permission.BLUETOOTH_CONNECT android.permission.BLUETOOTH_SCAN android.permission.BLUETOOTH_ADVERTISE
EXAMPLE_NEEDS_PROXY := true

include ../apk.mk
