// Code generated by javagen. DO NOT EDIT.

package display

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// VirtualDisplayConfigBrightnessListener wraps android.hardware.display.VirtualDisplayConfig$BrightnessListener.
type VirtualDisplayConfigBrightnessListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnBrightnessChanged calls android.hardware.display.VirtualDisplayConfig$BrightnessListener.onBrightnessChanged.
func (m *VirtualDisplayConfigBrightnessListener) OnBrightnessChanged(arg0 float32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVirtualDisplayConfigBrightnessListenerOnBrightnessChanged == nil {
			callErr = fmt.Errorf("android.hardware.display.VirtualDisplayConfig$BrightnessListener.onBrightnessChanged is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midVirtualDisplayConfigBrightnessListenerOnBrightnessChanged, jni.FloatValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.hardware.display.VirtualDisplayConfig$BrightnessListener.toString.
func (m *VirtualDisplayConfigBrightnessListener) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midVirtualDisplayConfigBrightnessListenerToString == nil {
			callErr = fmt.Errorf("android.hardware.display.VirtualDisplayConfig$BrightnessListener.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midVirtualDisplayConfigBrightnessListenerToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
