// Code generated by javagen. DO NOT EDIT.

package app

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/xaionaro-go/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	initOnce sync.Once
	initErr  error

	clsbundle                         *jni.GlobalRef
	midbundleClear                    jni.MethodID
	midbundleClone                    jni.MethodID
	midbundleDeepCopy                 jni.MethodID
	midbundleDescribeContents         jni.MethodID
	midbundleGetBinder                jni.MethodID
	midbundleGetBundle                jni.MethodID
	midbundleGetByte1                 jni.MethodID
	midbundleGetByte2_1               jni.MethodID
	midbundleGetByteArray             jni.MethodID
	midbundleGetChar1                 jni.MethodID
	midbundleGetChar2_1               jni.MethodID
	midbundleGetCharArray             jni.MethodID
	midbundleGetCharSequence1         jni.MethodID
	midbundleGetCharSequence2_1       jni.MethodID
	midbundleGetCharSequenceArray     jni.MethodID
	midbundleGetCharSequenceArrayList jni.MethodID
	midbundleGetClassLoader           jni.MethodID
	midbundleGetFloat1                jni.MethodID
	midbundleGetFloat2_1              jni.MethodID
	midbundleGetFloatArray            jni.MethodID
	midbundleGetIntegerArrayList      jni.MethodID
	midbundleGetParcelableArray       jni.MethodID
	midbundleGetSerializable          jni.MethodID
	midbundleGetShort1                jni.MethodID
	midbundleGetShort2_1              jni.MethodID
	midbundleGetShortArray            jni.MethodID
	midbundleGetSize                  jni.MethodID
	midbundleGetSizeF                 jni.MethodID
	midbundleGetStringArrayList       jni.MethodID
	midbundleHasFileDescriptors       jni.MethodID
	midbundlePutAll                   jni.MethodID
	midbundlePutBinder                jni.MethodID
	midbundlePutBundle                jni.MethodID
	midbundlePutByte                  jni.MethodID
	midbundlePutByteArray             jni.MethodID
	midbundlePutChar                  jni.MethodID
	midbundlePutCharArray             jni.MethodID
	midbundlePutCharSequence          jni.MethodID
	midbundlePutCharSequenceArray     jni.MethodID
	midbundlePutCharSequenceArrayList jni.MethodID
	midbundlePutFloat                 jni.MethodID
	midbundlePutFloatArray            jni.MethodID
	midbundlePutIntegerArrayList      jni.MethodID
	midbundlePutParcelable            jni.MethodID
	midbundlePutParcelableArray       jni.MethodID
	midbundlePutParcelableArrayList   jni.MethodID
	midbundlePutSerializable          jni.MethodID
	midbundlePutShort                 jni.MethodID
	midbundlePutShortArray            jni.MethodID
	midbundlePutSize                  jni.MethodID
	midbundlePutSizeF                 jni.MethodID
	midbundlePutSparseParcelableArray jni.MethodID
	midbundlePutStringArrayList       jni.MethodID
	midbundleReadFromParcel           jni.MethodID
	midbundleRemove                   jni.MethodID
	midbundleSetClassLoader           jni.MethodID
	midbundleWriteToParcel            jni.MethodID
)

// initSkipped records methods that were not found during init.
// These are typically methods that do not exist on the current device's
// Android API level. Calls to such methods will return an error at
// invocation time instead of preventing the entire service from loading.
var initSkipped []string

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("android/os/Bundle")
	if err != nil {
		return fmt.Errorf("find class android.os.Bundle: %w", err)
	}
	clsbundle = env.NewGlobalRef(&c.Object)

	midbundleClear, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "clear", "()V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.clear")
	}

	midbundleClone, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "clone", "()Ljava/lang/Object;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.clone")
	}

	midbundleDeepCopy, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "deepCopy", "()Landroid/os/Bundle;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.deepCopy")
	}

	midbundleDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.describeContents")
	}

	midbundleGetBinder, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getBinder", "(Ljava/lang/String;)Landroid/os/IBinder;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getBinder")
	}

	midbundleGetBundle, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getBundle", "(Ljava/lang/String;)Landroid/os/Bundle;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getBundle")
	}

	midbundleGetByte1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getByte", "(Ljava/lang/String;)B")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getByte")
	}

	midbundleGetByte2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getByte", "(Ljava/lang/String;B)Ljava/lang/Byte;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getByte")
	}

	midbundleGetByteArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getByteArray", "(Ljava/lang/String;)[B")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getByteArray")
	}

	midbundleGetChar1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getChar", "(Ljava/lang/String;)C")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getChar")
	}

	midbundleGetChar2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getChar", "(Ljava/lang/String;C)C")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getChar")
	}

	midbundleGetCharArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getCharArray", "(Ljava/lang/String;)[C")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getCharArray")
	}

	midbundleGetCharSequence1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getCharSequence", "(Ljava/lang/String;)Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getCharSequence")
	}

	midbundleGetCharSequence2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getCharSequence", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getCharSequence")
	}

	midbundleGetCharSequenceArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getCharSequenceArray", "(Ljava/lang/String;)[Ljava/lang/CharSequence;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getCharSequenceArray")
	}

	midbundleGetCharSequenceArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getCharSequenceArrayList", "(Ljava/lang/String;)Ljava/util/ArrayList;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getCharSequenceArrayList")
	}

	midbundleGetClassLoader, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getClassLoader", "()Ljava/lang/ClassLoader;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getClassLoader")
	}

	midbundleGetFloat1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getFloat", "(Ljava/lang/String;)F")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getFloat")
	}

	midbundleGetFloat2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getFloat", "(Ljava/lang/String;F)F")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getFloat")
	}

	midbundleGetFloatArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getFloatArray", "(Ljava/lang/String;)[F")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getFloatArray")
	}

	midbundleGetIntegerArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getIntegerArrayList", "(Ljava/lang/String;)Ljava/util/ArrayList;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getIntegerArrayList")
	}

	midbundleGetParcelableArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getParcelableArray", "(Ljava/lang/String;)[Landroid/os/Parcelable;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getParcelableArray")
	}

	midbundleGetSerializable, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getSerializable", "(Ljava/lang/String;)Ljava/io/Serializable;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getSerializable")
	}

	midbundleGetShort1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getShort", "(Ljava/lang/String;)S")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getShort")
	}

	midbundleGetShort2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getShort", "(Ljava/lang/String;S)S")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getShort")
	}

	midbundleGetShortArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getShortArray", "(Ljava/lang/String;)[S")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getShortArray")
	}

	midbundleGetSize, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getSize", "(Ljava/lang/String;)Landroid/util/Size;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getSize")
	}

	midbundleGetSizeF, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getSizeF", "(Ljava/lang/String;)Landroid/util/SizeF;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getSizeF")
	}

	midbundleGetStringArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "getStringArrayList", "(Ljava/lang/String;)Ljava/util/ArrayList;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.getStringArrayList")
	}

	midbundleHasFileDescriptors, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "hasFileDescriptors", "()Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.hasFileDescriptors")
	}

	midbundlePutAll, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putAll", "(Landroid/os/Bundle;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putAll")
	}

	midbundlePutBinder, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putBinder", "(Ljava/lang/String;Landroid/os/IBinder;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putBinder")
	}

	midbundlePutBundle, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putBundle", "(Ljava/lang/String;Landroid/os/Bundle;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putBundle")
	}

	midbundlePutByte, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putByte", "(Ljava/lang/String;B)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putByte")
	}

	midbundlePutByteArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putByteArray", "(Ljava/lang/String;[B)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putByteArray")
	}

	midbundlePutChar, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putChar", "(Ljava/lang/String;C)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putChar")
	}

	midbundlePutCharArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putCharArray", "(Ljava/lang/String;[C)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putCharArray")
	}

	midbundlePutCharSequence, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putCharSequence", "(Ljava/lang/String;Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putCharSequence")
	}

	midbundlePutCharSequenceArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putCharSequenceArray", "(Ljava/lang/String;[Ljava/lang/CharSequence;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putCharSequenceArray")
	}

	midbundlePutCharSequenceArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putCharSequenceArrayList", "(Ljava/lang/String;Ljava/util/ArrayList;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putCharSequenceArrayList")
	}

	midbundlePutFloat, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putFloat", "(Ljava/lang/String;F)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putFloat")
	}

	midbundlePutFloatArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putFloatArray", "(Ljava/lang/String;[F)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putFloatArray")
	}

	midbundlePutIntegerArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putIntegerArrayList", "(Ljava/lang/String;Ljava/util/ArrayList;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putIntegerArrayList")
	}

	midbundlePutParcelable, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putParcelable", "(Ljava/lang/String;Landroid/os/Parcelable;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putParcelable")
	}

	midbundlePutParcelableArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putParcelableArray", "(Ljava/lang/String;[Landroid/os/Parcelable;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putParcelableArray")
	}

	midbundlePutParcelableArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putParcelableArrayList", "(Ljava/lang/String;Ljava/util/ArrayList;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putParcelableArrayList")
	}

	midbundlePutSerializable, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putSerializable", "(Ljava/lang/String;Ljava/io/Serializable;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putSerializable")
	}

	midbundlePutShort, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putShort", "(Ljava/lang/String;S)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putShort")
	}

	midbundlePutShortArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putShortArray", "(Ljava/lang/String;[S)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putShortArray")
	}

	midbundlePutSize, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putSize", "(Ljava/lang/String;Landroid/util/Size;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putSize")
	}

	midbundlePutSizeF, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putSizeF", "(Ljava/lang/String;Landroid/util/SizeF;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putSizeF")
	}

	midbundlePutSparseParcelableArray, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putSparseParcelableArray", "(Ljava/lang/String;Landroid/util/SparseArray;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putSparseParcelableArray")
	}

	midbundlePutStringArrayList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "putStringArrayList", "(Ljava/lang/String;Ljava/util/ArrayList;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.putStringArrayList")
	}

	midbundleReadFromParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "readFromParcel", "(Landroid/os/Parcel;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.readFromParcel")
	}

	midbundleRemove, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "remove", "(Ljava/lang/String;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.remove")
	}

	midbundleSetClassLoader, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "setClassLoader", "(Ljava/lang/ClassLoader;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.setClassLoader")
	}

	midbundleWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsbundle)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
		initSkipped = append(initSkipped, "android.os.Bundle.writeToParcel")
	}

	return nil
}
