// Code generated by javagen. DO NOT EDIT.

package app

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// LauncherActivity wraps android.app.LauncherActivity.
type LauncherActivity struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// MakeListItems calls android.app.LauncherActivity.makeListItems.
func (m *LauncherActivity) MakeListItems() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherActivityMakeListItems == nil {
			callErr = fmt.Errorf("android.app.LauncherActivity.makeListItems is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherActivityMakeListItems,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// SetTitle1 calls android.app.LauncherActivity.setTitle.
func (m *LauncherActivity) SetTitle1(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherActivitySetTitle1 == nil {
			callErr = fmt.Errorf("android.app.LauncherActivity.setTitle is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherActivitySetTitle1, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetTitle1_1 calls android.app.LauncherActivity.setTitle.
func (m *LauncherActivity) SetTitle1_1(arg0 string) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherActivitySetTitle1_1 == nil {
			callErr = fmt.Errorf("android.app.LauncherActivity.setTitle is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		callErr = env.CallVoidMethod(
			m.Obj,
			midLauncherActivitySetTitle1_1, jni.ObjectValue(&jArg0.Object),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.app.LauncherActivity.toString.
func (m *LauncherActivity) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midLauncherActivityToString == nil {
			callErr = fmt.Errorf("android.app.LauncherActivity.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midLauncherActivityToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
