// Code generated by javagen. DO NOT EDIT.

package display

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ViewOnClickListener wraps android.view.View$OnClickListener.
type ViewOnClickListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnClick calls android.view.View$OnClickListener.onClick.
func (m *ViewOnClickListener) OnClick(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midViewOnClickListenerOnClick == nil {
			callErr = fmt.Errorf("android.view.View$OnClickListener.onClick is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midViewOnClickListenerOnClick, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}
