// Code generated by javagen. DO NOT EDIT.

package inline

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ContentViewSurfaceControlCallback wraps android.widget.inline.InlineContentView$SurfaceControlCallback.
type ContentViewSurfaceControlCallback struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnCreated calls android.widget.inline.InlineContentView$SurfaceControlCallback.onCreated.
func (m *ContentViewSurfaceControlCallback) OnCreated(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContentViewSurfaceControlCallbackOnCreated == nil {
			callErr = fmt.Errorf("android.widget.inline.InlineContentView$SurfaceControlCallback.onCreated is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midContentViewSurfaceControlCallbackOnCreated, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnDestroyed calls android.widget.inline.InlineContentView$SurfaceControlCallback.onDestroyed.
func (m *ContentViewSurfaceControlCallback) OnDestroyed(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContentViewSurfaceControlCallbackOnDestroyed == nil {
			callErr = fmt.Errorf("android.widget.inline.InlineContentView$SurfaceControlCallback.onDestroyed is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midContentViewSurfaceControlCallbackOnDestroyed, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ToString calls android.widget.inline.InlineContentView$SurfaceControlCallback.toString.
func (m *ContentViewSurfaceControlCallback) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContentViewSurfaceControlCallbackToString == nil {
			callErr = fmt.Errorf("android.widget.inline.InlineContentView$SurfaceControlCallback.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midContentViewSurfaceControlCallbackToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
