// Code generated by javagen. DO NOT EDIT.

package projection

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/xaionaro-go/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

var (
	initOnce sync.Once
	initErr  error

	clsmediaProjection                   *jni.GlobalRef
	midmediaProjectionStop               jni.MethodID
	midmediaProjectionUnregisterCallback jni.MethodID
)

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("android/media/projection/MediaProjection")
	if err != nil {
		return fmt.Errorf("find class android.media.projection.MediaProjection: %w", err)
	}
	clsmediaProjection = env.NewGlobalRef(&c.Object)

	midmediaProjectionStop, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsmediaProjection)), "stop", "()V")
	if err != nil {
		return fmt.Errorf("get method android.media.projection.MediaProjection.stop: %w", err)
	}

	midmediaProjectionUnregisterCallback, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsmediaProjection)), "unregisterCallback", "(Landroid/media/projection/MediaProjection$Callback;)V")
	if err != nil {
		return fmt.Errorf("get method android.media.projection.MediaProjection.unregisterCallback: %w", err)
	}

	return nil
}
