// Code generated by javagen. DO NOT EDIT.

package projection

import (
	"fmt"
	"unsafe"

	"github.com/xaionaro-go/jni"
	"github.com/xaionaro-go/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// mediaProjectionManager wraps android.media.projection.MediaProjectionManager.
type mediaProjectionManager struct {
	VM  *jni.VM
	Ctx *app.Context
	Obj *jni.GlobalRef
}

// NewmediaProjectionManager obtains android.media.projection.MediaProjectionManager from the Android system service manager.
func NewmediaProjectionManager(ctx *app.Context) (*mediaProjectionManager, error) {
	if ctx == nil {
		return nil, fmt.Errorf("mediaProjectionManager: nil Context")
	}
	var mgr mediaProjectionManager
	mgr.VM = ctx.VM
	mgr.Ctx = ctx

	err := mgr.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		svc, err := ctx.GetSystemService("media_projection")
		if err != nil {
			return err
		}
		if svc == nil || svc.Ref() == 0 {
			return fmt.Errorf("media_projection service not available")
		}
		mgr.Obj = env.NewGlobalRef(svc)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &mgr, nil
}

// Close releases the global reference to the underlying Java object.
// After Close, the mediaProjectionManager must not be used.
func (m *mediaProjectionManager) Close() {
	if m.Obj != nil {
		m.VM.Do(func(env *jni.Env) error {
			env.DeleteGlobalRef(m.Obj)
			m.Obj = nil
			return nil
		})
	}
}

// CreateScreenCaptureIntent0 calls android.media.projection.MediaProjectionManager.createScreenCaptureIntent.
func (m *mediaProjectionManager) CreateScreenCaptureIntent0() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midmediaProjectionManagerCreateScreenCaptureIntent0 == nil {
			callErr = fmt.Errorf("android.media.projection.MediaProjectionManager.createScreenCaptureIntent is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midmediaProjectionManagerCreateScreenCaptureIntent0,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// CreateScreenCaptureIntent1_1 calls android.media.projection.MediaProjectionManager.createScreenCaptureIntent.
func (m *mediaProjectionManager) CreateScreenCaptureIntent1_1(arg0 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midmediaProjectionManagerCreateScreenCaptureIntent1_1 == nil {
			callErr = fmt.Errorf("android.media.projection.MediaProjectionManager.createScreenCaptureIntent is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midmediaProjectionManagerCreateScreenCaptureIntent1_1, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetMediaProjection calls android.media.projection.MediaProjectionManager.getMediaProjection.
func (m *mediaProjectionManager) GetMediaProjection(arg0 int32, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midmediaProjectionManagerGetMediaProjection == nil {
			callErr = fmt.Errorf("android.media.projection.MediaProjectionManager.getMediaProjection is not available on this device")
			return callErr
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midmediaProjectionManagerGetMediaProjection, jni.IntValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
