// Code generated by javagen. DO NOT EDIT.

package consts

const (
	DataShareErrorConcurrentRequest  int = 2
	DataShareErrorTimeoutInterrupted int = 3
	DataShareErrorUnknown            int = 1
	Creator                          int = 0
	FlagIsPrefix                     int = 1
	FlagIsRegex                      int = 2
)
