// Code generated by javagen. DO NOT EDIT.

package devicelock

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DeviceId wraps android.devicelock.DeviceId.
type DeviceId struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetId calls android.devicelock.DeviceId.getId.
func (m *DeviceId) GetId() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDeviceIdGetId == nil {
			callErr = fmt.Errorf("android.devicelock.DeviceId.getId is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDeviceIdGetId,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetType calls android.devicelock.DeviceId.getType.
func (m *DeviceId) GetType() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDeviceIdGetType == nil {
			callErr = fmt.Errorf("android.devicelock.DeviceId.getType is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDeviceIdGetType,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// ToString calls android.devicelock.DeviceId.toString.
func (m *DeviceId) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDeviceIdToString == nil {
			callErr = fmt.Errorf("android.devicelock.DeviceId.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midDeviceIdToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
