// Code generated by javagen. DO NOT EDIT.

package os

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// PerformanceHintManagerSession wraps android.os.PerformanceHintManager$Session.
type PerformanceHintManagerSession struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Close calls android.os.PerformanceHintManager$Session.close.
func (m *PerformanceHintManagerSession) Close() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionClose == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.close is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionClose,
		)
		return callErr
	})
	return callErr
}

// ReportActualWorkDuration1 calls android.os.PerformanceHintManager$Session.reportActualWorkDuration.
func (m *PerformanceHintManagerSession) ReportActualWorkDuration1(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionReportActualWorkDuration1 == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.reportActualWorkDuration is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionReportActualWorkDuration1, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// ReportActualWorkDuration1_1 calls android.os.PerformanceHintManager$Session.reportActualWorkDuration.
func (m *PerformanceHintManagerSession) ReportActualWorkDuration1_1(arg0 int64) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionReportActualWorkDuration1_1 == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.reportActualWorkDuration is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionReportActualWorkDuration1_1, jni.LongValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetPreferPowerEfficiency calls android.os.PerformanceHintManager$Session.setPreferPowerEfficiency.
func (m *PerformanceHintManagerSession) SetPreferPowerEfficiency(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionSetPreferPowerEfficiency == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.setPreferPowerEfficiency is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionSetPreferPowerEfficiency, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}

// SetThreads calls android.os.PerformanceHintManager$Session.setThreads.
func (m *PerformanceHintManagerSession) SetThreads(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionSetThreads == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.setThreads is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionSetThreads, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// UpdateTargetWorkDuration calls android.os.PerformanceHintManager$Session.updateTargetWorkDuration.
func (m *PerformanceHintManagerSession) UpdateTargetWorkDuration(arg0 int64) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midPerformanceHintManagerSessionUpdateTargetWorkDuration == nil {
			callErr = fmt.Errorf("android.os.PerformanceHintManager$Session.updateTargetWorkDuration is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midPerformanceHintManagerSessionUpdateTargetWorkDuration, jni.LongValue(arg0),
		)
		return callErr
	})
	return callErr
}
