// Code generated by javagen. DO NOT EDIT.

package usb

import (
	"fmt"
	"sync"
	"unsafe"

	"github.com/AndroidGoLab/jni"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
)

// jniTrue is the JNI representation of a true boolean value.
const jniTrue uint8 = 1

var (
	initOnce sync.Once
	initErr  error

	clsEndpoint                  *jni.GlobalRef
	midEndpointDescribeContents  jni.MethodID
	midEndpointGetAddress        jni.MethodID
	midEndpointGetAttributes     jni.MethodID
	midEndpointGetDirection      jni.MethodID
	midEndpointGetEndpointNumber jni.MethodID
	midEndpointGetInterval       jni.MethodID
	midEndpointGetMaxPacketSize  jni.MethodID
	midEndpointGetType           jni.MethodID
	midEndpointToString          jni.MethodID
	midEndpointWriteToParcel     jni.MethodID

	clsDeviceConnection                   *jni.GlobalRef
	midDeviceConnectionBulkTransfer4      jni.MethodID
	midDeviceConnectionBulkTransfer5_1    jni.MethodID
	midDeviceConnectionClaimInterface     jni.MethodID
	midDeviceConnectionClose              jni.MethodID
	midDeviceConnectionControlTransfer7   jni.MethodID
	midDeviceConnectionControlTransfer8_1 jni.MethodID
	midDeviceConnectionGetFileDescriptor  jni.MethodID
	midDeviceConnectionGetRawDescriptors  jni.MethodID
	midDeviceConnectionGetSerial          jni.MethodID
	midDeviceConnectionReleaseInterface   jni.MethodID
	midDeviceConnectionRequestWait0       jni.MethodID
	midDeviceConnectionRequestWait1_1     jni.MethodID
	midDeviceConnectionSetConfiguration   jni.MethodID
	midDeviceConnectionSetInterface       jni.MethodID

	clsDevice                      *jni.GlobalRef
	midDeviceDescribeContents      jni.MethodID
	midDeviceEquals                jni.MethodID
	midDeviceGetConfiguration      jni.MethodID
	midDeviceGetConfigurationCount jni.MethodID
	midDeviceGetDeviceClass        jni.MethodID
	midDeviceGetDeviceId0          jni.MethodID
	midDeviceGetDeviceName0        jni.MethodID
	midDeviceGetDeviceProtocol     jni.MethodID
	midDeviceGetDeviceSubclass     jni.MethodID
	midDeviceGetInterface          jni.MethodID
	midDeviceGetInterfaceCount     jni.MethodID
	midDeviceGetManufacturerName   jni.MethodID
	midDeviceGetProductId          jni.MethodID
	midDeviceGetProductName        jni.MethodID
	midDeviceGetSerialNumber       jni.MethodID
	midDeviceGetVendorId           jni.MethodID
	midDeviceGetVersion            jni.MethodID
	midDeviceHashCode              jni.MethodID
	midDeviceToString              jni.MethodID
	midDeviceWriteToParcel         jni.MethodID
	midDeviceGetDeviceId1_1        jni.MethodID
	midDeviceGetDeviceName1_1      jni.MethodID

	clsManager                          *jni.GlobalRef
	midManagerGetAccessoryList          jni.MethodID
	midManagerHasPermission1            jni.MethodID
	midManagerHasPermission1_1          jni.MethodID
	midManagerOpenAccessory             jni.MethodID
	midManagerOpenAccessoryInputStream  jni.MethodID
	midManagerOpenAccessoryOutputStream jni.MethodID
	midManagerOpenDevice                jni.MethodID
	midManagerRequestPermission2        jni.MethodID
	midManagerRequestPermission2_1      jni.MethodID

	clsInterface                     *jni.GlobalRef
	midInterfaceDescribeContents     jni.MethodID
	midInterfaceGetAlternateSetting  jni.MethodID
	midInterfaceGetEndpoint          jni.MethodID
	midInterfaceGetEndpointCount     jni.MethodID
	midInterfaceGetId                jni.MethodID
	midInterfaceGetInterfaceClass    jni.MethodID
	midInterfaceGetInterfaceProtocol jni.MethodID
	midInterfaceGetInterfaceSubclass jni.MethodID
	midInterfaceGetName              jni.MethodID
	midInterfaceToString             jni.MethodID
	midInterfaceWriteToParcel        jni.MethodID
)

func ensureInit(env *jni.Env) error {
	initOnce.Do(func() {
		initErr = doInit(env)
	})
	return initErr
}

// Init resolves all JNI class and method references for this package.
// It is safe to call multiple times (uses sync.Once internally).
// Exported for E2E testing on Android.
func Init(env *jni.Env) error {
	return ensureInit(env)
}

func doInit(env *jni.Env) error {
	var c *jni.Class
	var err error

	c, err = env.FindClass("android/hardware/usb/UsbEndpoint")
	if err != nil {
		return fmt.Errorf("find class android.hardware.usb.UsbEndpoint: %w", err)
	}
	clsEndpoint = env.NewGlobalRef(&c.Object)

	midEndpointDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetAddress, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getAddress", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetAttributes, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getAttributes", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetDirection, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getDirection", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetEndpointNumber, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getEndpointNumber", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetInterval, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getInterval", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetMaxPacketSize, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getMaxPacketSize", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointGetType, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "getType", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "toString", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midEndpointWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsEndpoint)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	c, err = env.FindClass("android/hardware/usb/UsbDeviceConnection")
	if err != nil {
		return fmt.Errorf("find class android.hardware.usb.UsbDeviceConnection: %w", err)
	}
	clsDeviceConnection = env.NewGlobalRef(&c.Object)

	midDeviceConnectionBulkTransfer4, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "bulkTransfer", "(Landroid/hardware/usb/UsbEndpoint;[BII)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionBulkTransfer5_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "bulkTransfer", "(Landroid/hardware/usb/UsbEndpoint;[BIII)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionClaimInterface, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "claimInterface", "(Landroid/hardware/usb/UsbInterface;Z)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionClose, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "close", "()V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionControlTransfer7, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "controlTransfer", "(IIII[BII)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionControlTransfer8_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "controlTransfer", "(IIII[BIII)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionGetFileDescriptor, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "getFileDescriptor", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionGetRawDescriptors, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "getRawDescriptors", "()[B")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionGetSerial, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "getSerial", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionReleaseInterface, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "releaseInterface", "(Landroid/hardware/usb/UsbInterface;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionRequestWait0, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "requestWait", "()Landroid/hardware/usb/UsbRequest;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionRequestWait1_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "requestWait", "(J)Landroid/hardware/usb/UsbRequest;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionSetConfiguration, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "setConfiguration", "(Landroid/hardware/usb/UsbConfiguration;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceConnectionSetInterface, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDeviceConnection)), "setInterface", "(Landroid/hardware/usb/UsbInterface;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	c, err = env.FindClass("android/hardware/usb/UsbDevice")
	if err != nil {
		return fmt.Errorf("find class android.hardware.usb.UsbDevice: %w", err)
	}
	clsDevice = env.NewGlobalRef(&c.Object)

	midDeviceDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceEquals, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "equals", "(Ljava/lang/Object;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetConfiguration, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getConfiguration", "(I)Landroid/hardware/usb/UsbConfiguration;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetConfigurationCount, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getConfigurationCount", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceClass, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceClass", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceId0, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceId", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceName0, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceName", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceProtocol, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceProtocol", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceSubclass, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceSubclass", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetInterface, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getInterface", "(I)Landroid/hardware/usb/UsbInterface;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetInterfaceCount, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getInterfaceCount", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetManufacturerName, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getManufacturerName", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetProductId, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getProductId", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetProductName, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getProductName", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetSerialNumber, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getSerialNumber", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetVendorId, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getVendorId", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetVersion, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getVersion", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceHashCode, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "hashCode", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "toString", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceId1_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceId", "(Ljava/lang/String;)I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midDeviceGetDeviceName1_1, err = env.GetStaticMethodID((*jni.Class)(unsafe.Pointer(clsDevice)), "getDeviceName", "(I)Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	c, err = env.FindClass("android/hardware/usb/UsbManager")
	if err != nil {
		return fmt.Errorf("find class android.hardware.usb.UsbManager: %w", err)
	}
	clsManager = env.NewGlobalRef(&c.Object)

	midManagerGetAccessoryList, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "getAccessoryList", "()[Landroid/hardware/usb/UsbAccessory;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerHasPermission1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "hasPermission", "(Landroid/hardware/usb/UsbAccessory;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerHasPermission1_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "hasPermission", "(Landroid/hardware/usb/UsbDevice;)Z")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerOpenAccessory, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "openAccessory", "(Landroid/hardware/usb/UsbAccessory;)Landroid/os/ParcelFileDescriptor;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerOpenAccessoryInputStream, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "openAccessoryInputStream", "(Landroid/hardware/usb/UsbAccessory;)Ljava/io/InputStream;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerOpenAccessoryOutputStream, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "openAccessoryOutputStream", "(Landroid/hardware/usb/UsbAccessory;)Ljava/io/OutputStream;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerOpenDevice, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "openDevice", "(Landroid/hardware/usb/UsbDevice;)Landroid/hardware/usb/UsbDeviceConnection;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerRequestPermission2, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "requestPermission", "(Landroid/hardware/usb/UsbAccessory;Landroid/app/PendingIntent;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midManagerRequestPermission2_1, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsManager)), "requestPermission", "(Landroid/hardware/usb/UsbDevice;Landroid/app/PendingIntent;)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	c, err = env.FindClass("android/hardware/usb/UsbInterface")
	if err != nil {
		return fmt.Errorf("find class android.hardware.usb.UsbInterface: %w", err)
	}
	clsInterface = env.NewGlobalRef(&c.Object)

	midInterfaceDescribeContents, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "describeContents", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetAlternateSetting, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getAlternateSetting", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetEndpoint, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getEndpoint", "(I)Landroid/hardware/usb/UsbEndpoint;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetEndpointCount, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getEndpointCount", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetId, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getId", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetInterfaceClass, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getInterfaceClass", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetInterfaceProtocol, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getInterfaceProtocol", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetInterfaceSubclass, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getInterfaceSubclass", "()I")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceGetName, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "getName", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceToString, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "toString", "()Ljava/lang/String;")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	midInterfaceWriteToParcel, err = env.GetMethodID((*jni.Class)(unsafe.Pointer(clsInterface)), "writeToParcel", "(Landroid/os/Parcel;I)V")
	if err != nil {
		// Method may not exist on this device's API level; skip and
		// report at invocation time instead of failing the entire init.
		env.ExceptionClear()
	}

	return nil
}
