// Code generated by javagen. DO NOT EDIT.

package preference

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ManagerOnActivityDestroyListener wraps android.preference.PreferenceManager$OnActivityDestroyListener.
type ManagerOnActivityDestroyListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnActivityDestroy calls android.preference.PreferenceManager$OnActivityDestroyListener.onActivityDestroy.
func (m *ManagerOnActivityDestroyListener) OnActivityDestroy() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midManagerOnActivityDestroyListenerOnActivityDestroy == nil {
			callErr = fmt.Errorf("android.preference.PreferenceManager$OnActivityDestroyListener.onActivityDestroy is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midManagerOnActivityDestroyListenerOnActivityDestroy,
		)
		return callErr
	})
	return callErr
}
