// Code generated by javagen. DO NOT EDIT.

package animation

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// TypeEvaluator wraps android.animation.TypeEvaluator.
type TypeEvaluator struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls android.animation.TypeEvaluator.toString.
func (m *TypeEvaluator) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTypeEvaluatorToString == nil {
			callErr = fmt.Errorf("android.animation.TypeEvaluator.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midTypeEvaluatorToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
