// Code generated by javagen. DO NOT EDIT.

package omapi

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Reader wraps android.se.omapi.Reader.
type Reader struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// CloseSessions calls android.se.omapi.Reader.closeSessions.
func (m *Reader) CloseSessions() error {

	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midReaderCloseSessions == nil {
			callErr = fmt.Errorf("android.se.omapi.Reader.closeSessions is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midReaderCloseSessions,
		)
		return callErr
	})
	return callErr
}

// GetName calls android.se.omapi.Reader.getName.
func (m *Reader) GetName() (string, error) {
	var result string
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midReaderGetName == nil {
			callErr = fmt.Errorf("android.se.omapi.Reader.getName is not available on this device")
			return callErr
		}
		resultObj, callErr := env.CallObjectMethod(
			m.Obj,
			midReaderGetName,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetSEService calls android.se.omapi.Reader.getSEService.
func (m *Reader) GetSEService() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midReaderGetSEService == nil {
			callErr = fmt.Errorf("android.se.omapi.Reader.getSEService is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midReaderGetSEService,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsSecureElementPresent calls android.se.omapi.Reader.isSecureElementPresent.
func (m *Reader) IsSecureElementPresent() (bool, error) {
	var result bool
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midReaderIsSecureElementPresent == nil {
			callErr = fmt.Errorf("android.se.omapi.Reader.isSecureElementPresent is not available on this device")
			return callErr
		}
		resultRaw, callErr := env.CallBooleanMethod(
			m.Obj,
			midReaderIsSecureElementPresent,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// OpenSession calls android.se.omapi.Reader.openSession.
func (m *Reader) OpenSession() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midReaderOpenSession == nil {
			callErr = fmt.Errorf("android.se.omapi.Reader.openSession is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midReaderOpenSession,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
