// Code generated by javagen. DO NOT EDIT.

package audiomanager

const (
	TypeAuxLine            = 0
	TypeBleBroadcast       = 0
	TypeBleHeadset         = 0
	TypeBleSpeaker         = 0
	TypeBluetoothA2dp      = 0
	TypeBluetoothSco       = 0
	TypeBuiltinEarpiece    = 0
	TypeBuiltinMic         = 0
	TypeBuiltinSpeaker     = 0
	TypeBuiltinSpeakerSafe = 0
	TypeBus                = 0
	TypeDock               = 0
	TypeDockAnalog         = 0
	TypeFm                 = 0
	TypeFmTuner            = 0
	TypeHdmi               = 0
	TypeHdmiArc            = 0
	TypeHdmiEarc           = 0
	TypeHearingAid         = 0
	TypeIp                 = 0
	TypeLineAnalog         = 0
	TypeLineDigital        = 0
	TypeMultichannelGroup  = 0
	TypeRemoteSubmix       = 0
	TypeTelephony          = 0
	TypeTvTuner            = 0
	TypeUnknown            = 0
	TypeUsbAccessory       = 0
	TypeUsbDevice          = 0
	TypeUsbHeadset         = 0
	TypeWiredHeadphones    = 0
	TypeWiredHeadset       = 0
)
