EXAMPLE_NAME := camera_record
EXAMPLE_PERMISSIONS := android.permission.CAMERA android.permission.RECORD_AUDIO
EXAMPLE_NEEDS_PROXY := true
EXAMPLE_EXTRA_JAVA := $(wildcard ../common/java/center/dx/jni/generated/*.java)

include ../apk.mk
