// Code generated by javagen. DO NOT EDIT.

package pdf

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// DocumentPageInfo wraps android.graphics.pdf.PdfDocument$PageInfo.
type DocumentPageInfo struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetContentRect calls android.graphics.pdf.PdfDocument$PageInfo.getContentRect.
func (m *DocumentPageInfo) GetContentRect() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDocumentPageInfoGetContentRect == nil {
			callErr = fmt.Errorf("android.graphics.pdf.PdfDocument$PageInfo.getContentRect is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midDocumentPageInfoGetContentRect,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetPageHeight calls android.graphics.pdf.PdfDocument$PageInfo.getPageHeight.
func (m *DocumentPageInfo) GetPageHeight() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDocumentPageInfoGetPageHeight == nil {
			callErr = fmt.Errorf("android.graphics.pdf.PdfDocument$PageInfo.getPageHeight is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDocumentPageInfoGetPageHeight,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetPageNumber calls android.graphics.pdf.PdfDocument$PageInfo.getPageNumber.
func (m *DocumentPageInfo) GetPageNumber() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDocumentPageInfoGetPageNumber == nil {
			callErr = fmt.Errorf("android.graphics.pdf.PdfDocument$PageInfo.getPageNumber is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDocumentPageInfoGetPageNumber,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetPageWidth calls android.graphics.pdf.PdfDocument$PageInfo.getPageWidth.
func (m *DocumentPageInfo) GetPageWidth() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midDocumentPageInfoGetPageWidth == nil {
			callErr = fmt.Errorf("android.graphics.pdf.PdfDocument$PageInfo.getPageWidth is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midDocumentPageInfoGetPageWidth,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
