// Code generated by protogen. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/nsd/nsd.proto

package nsd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NsdServiceInfoService_DescribeContents_FullMethodName = "/nsd.NsdServiceInfoService/DescribeContents"
	NsdServiceInfoService_GetHost_FullMethodName          = "/nsd.NsdServiceInfoService/GetHost"
	NsdServiceInfoService_GetHostAddresses_FullMethodName = "/nsd.NsdServiceInfoService/GetHostAddresses"
	NsdServiceInfoService_GetHostname_FullMethodName      = "/nsd.NsdServiceInfoService/GetHostname"
	NsdServiceInfoService_GetNetwork_FullMethodName       = "/nsd.NsdServiceInfoService/GetNetwork"
	NsdServiceInfoService_GetPort_FullMethodName          = "/nsd.NsdServiceInfoService/GetPort"
	NsdServiceInfoService_GetServiceName_FullMethodName   = "/nsd.NsdServiceInfoService/GetServiceName"
	NsdServiceInfoService_GetServiceType_FullMethodName   = "/nsd.NsdServiceInfoService/GetServiceType"
	NsdServiceInfoService_GetSubtypes_FullMethodName      = "/nsd.NsdServiceInfoService/GetSubtypes"
	NsdServiceInfoService_RemoveAttribute_FullMethodName  = "/nsd.NsdServiceInfoService/RemoveAttribute"
	NsdServiceInfoService_SetAttribute_FullMethodName     = "/nsd.NsdServiceInfoService/SetAttribute"
	NsdServiceInfoService_SetHost_FullMethodName          = "/nsd.NsdServiceInfoService/SetHost"
	NsdServiceInfoService_SetHostAddresses_FullMethodName = "/nsd.NsdServiceInfoService/SetHostAddresses"
	NsdServiceInfoService_SetNetwork_FullMethodName       = "/nsd.NsdServiceInfoService/SetNetwork"
	NsdServiceInfoService_SetPort_FullMethodName          = "/nsd.NsdServiceInfoService/SetPort"
	NsdServiceInfoService_SetServiceName_FullMethodName   = "/nsd.NsdServiceInfoService/SetServiceName"
	NsdServiceInfoService_SetServiceType_FullMethodName   = "/nsd.NsdServiceInfoService/SetServiceType"
	NsdServiceInfoService_SetSubtypes_FullMethodName      = "/nsd.NsdServiceInfoService/SetSubtypes"
	NsdServiceInfoService_ToString_FullMethodName         = "/nsd.NsdServiceInfoService/ToString"
	NsdServiceInfoService_WriteToParcel_FullMethodName    = "/nsd.NsdServiceInfoService/WriteToParcel"
)

// NsdServiceInfoServiceClient is the client API for NsdServiceInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NsdServiceInfoServiceClient interface {
	DescribeContents(ctx context.Context, in *DescribeContentsRequest, opts ...grpc.CallOption) (*DescribeContentsResponse, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error)
	GetHostAddresses(ctx context.Context, in *GetHostAddressesRequest, opts ...grpc.CallOption) (*GetHostAddressesResponse, error)
	GetHostname(ctx context.Context, in *GetHostnameRequest, opts ...grpc.CallOption) (*GetHostnameResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	GetPort(ctx context.Context, in *GetPortRequest, opts ...grpc.CallOption) (*GetPortResponse, error)
	GetServiceName(ctx context.Context, in *GetServiceNameRequest, opts ...grpc.CallOption) (*GetServiceNameResponse, error)
	GetServiceType(ctx context.Context, in *GetServiceTypeRequest, opts ...grpc.CallOption) (*GetServiceTypeResponse, error)
	GetSubtypes(ctx context.Context, in *GetSubtypesRequest, opts ...grpc.CallOption) (*GetSubtypesResponse, error)
	RemoveAttribute(ctx context.Context, in *RemoveAttributeRequest, opts ...grpc.CallOption) (*RemoveAttributeResponse, error)
	SetAttribute(ctx context.Context, in *SetAttributeRequest, opts ...grpc.CallOption) (*SetAttributeResponse, error)
	SetHost(ctx context.Context, in *SetHostRequest, opts ...grpc.CallOption) (*SetHostResponse, error)
	SetHostAddresses(ctx context.Context, in *SetHostAddressesRequest, opts ...grpc.CallOption) (*SetHostAddressesResponse, error)
	SetNetwork(ctx context.Context, in *SetNetworkRequest, opts ...grpc.CallOption) (*SetNetworkResponse, error)
	SetPort(ctx context.Context, in *SetPortRequest, opts ...grpc.CallOption) (*SetPortResponse, error)
	SetServiceName(ctx context.Context, in *SetServiceNameRequest, opts ...grpc.CallOption) (*SetServiceNameResponse, error)
	SetServiceType(ctx context.Context, in *SetServiceTypeRequest, opts ...grpc.CallOption) (*SetServiceTypeResponse, error)
	SetSubtypes(ctx context.Context, in *SetSubtypesRequest, opts ...grpc.CallOption) (*SetSubtypesResponse, error)
	ToString(ctx context.Context, in *ToStringRequest, opts ...grpc.CallOption) (*ToStringResponse, error)
	WriteToParcel(ctx context.Context, in *WriteToParcelRequest, opts ...grpc.CallOption) (*WriteToParcelResponse, error)
}

type nsdServiceInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNsdServiceInfoServiceClient(cc grpc.ClientConnInterface) NsdServiceInfoServiceClient {
	return &nsdServiceInfoServiceClient{cc}
}

func (c *nsdServiceInfoServiceClient) DescribeContents(ctx context.Context, in *DescribeContentsRequest, opts ...grpc.CallOption) (*DescribeContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeContentsResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_DescribeContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetHostAddresses(ctx context.Context, in *GetHostAddressesRequest, opts ...grpc.CallOption) (*GetHostAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostAddressesResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetHostAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetHostname(ctx context.Context, in *GetHostnameRequest, opts ...grpc.CallOption) (*GetHostnameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostnameResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetHostname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetPort(ctx context.Context, in *GetPortRequest, opts ...grpc.CallOption) (*GetPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPortResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetServiceName(ctx context.Context, in *GetServiceNameRequest, opts ...grpc.CallOption) (*GetServiceNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceNameResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetServiceName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetServiceType(ctx context.Context, in *GetServiceTypeRequest, opts ...grpc.CallOption) (*GetServiceTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceTypeResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetServiceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) GetSubtypes(ctx context.Context, in *GetSubtypesRequest, opts ...grpc.CallOption) (*GetSubtypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubtypesResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_GetSubtypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) RemoveAttribute(ctx context.Context, in *RemoveAttributeRequest, opts ...grpc.CallOption) (*RemoveAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAttributeResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_RemoveAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetAttribute(ctx context.Context, in *SetAttributeRequest, opts ...grpc.CallOption) (*SetAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAttributeResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetHost(ctx context.Context, in *SetHostRequest, opts ...grpc.CallOption) (*SetHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHostResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetHostAddresses(ctx context.Context, in *SetHostAddressesRequest, opts ...grpc.CallOption) (*SetHostAddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetHostAddressesResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetHostAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetNetwork(ctx context.Context, in *SetNetworkRequest, opts ...grpc.CallOption) (*SetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNetworkResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetPort(ctx context.Context, in *SetPortRequest, opts ...grpc.CallOption) (*SetPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPortResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetServiceName(ctx context.Context, in *SetServiceNameRequest, opts ...grpc.CallOption) (*SetServiceNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceNameResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetServiceName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetServiceType(ctx context.Context, in *SetServiceTypeRequest, opts ...grpc.CallOption) (*SetServiceTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceTypeResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetServiceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) SetSubtypes(ctx context.Context, in *SetSubtypesRequest, opts ...grpc.CallOption) (*SetSubtypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSubtypesResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_SetSubtypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) ToString(ctx context.Context, in *ToStringRequest, opts ...grpc.CallOption) (*ToStringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToStringResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_ToString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nsdServiceInfoServiceClient) WriteToParcel(ctx context.Context, in *WriteToParcelRequest, opts ...grpc.CallOption) (*WriteToParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteToParcelResponse)
	err := c.cc.Invoke(ctx, NsdServiceInfoService_WriteToParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NsdServiceInfoServiceServer is the server API for NsdServiceInfoService service.
// All implementations must embed UnimplementedNsdServiceInfoServiceServer
// for forward compatibility.
type NsdServiceInfoServiceServer interface {
	DescribeContents(context.Context, *DescribeContentsRequest) (*DescribeContentsResponse, error)
	GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error)
	GetHostAddresses(context.Context, *GetHostAddressesRequest) (*GetHostAddressesResponse, error)
	GetHostname(context.Context, *GetHostnameRequest) (*GetHostnameResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	GetPort(context.Context, *GetPortRequest) (*GetPortResponse, error)
	GetServiceName(context.Context, *GetServiceNameRequest) (*GetServiceNameResponse, error)
	GetServiceType(context.Context, *GetServiceTypeRequest) (*GetServiceTypeResponse, error)
	GetSubtypes(context.Context, *GetSubtypesRequest) (*GetSubtypesResponse, error)
	RemoveAttribute(context.Context, *RemoveAttributeRequest) (*RemoveAttributeResponse, error)
	SetAttribute(context.Context, *SetAttributeRequest) (*SetAttributeResponse, error)
	SetHost(context.Context, *SetHostRequest) (*SetHostResponse, error)
	SetHostAddresses(context.Context, *SetHostAddressesRequest) (*SetHostAddressesResponse, error)
	SetNetwork(context.Context, *SetNetworkRequest) (*SetNetworkResponse, error)
	SetPort(context.Context, *SetPortRequest) (*SetPortResponse, error)
	SetServiceName(context.Context, *SetServiceNameRequest) (*SetServiceNameResponse, error)
	SetServiceType(context.Context, *SetServiceTypeRequest) (*SetServiceTypeResponse, error)
	SetSubtypes(context.Context, *SetSubtypesRequest) (*SetSubtypesResponse, error)
	ToString(context.Context, *ToStringRequest) (*ToStringResponse, error)
	WriteToParcel(context.Context, *WriteToParcelRequest) (*WriteToParcelResponse, error)
	mustEmbedUnimplementedNsdServiceInfoServiceServer()
}

// UnimplementedNsdServiceInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNsdServiceInfoServiceServer struct{}

func (UnimplementedNsdServiceInfoServiceServer) DescribeContents(context.Context, *DescribeContentsRequest) (*DescribeContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeContents not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetHostAddresses(context.Context, *GetHostAddressesRequest) (*GetHostAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostAddresses not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetHostname(context.Context, *GetHostnameRequest) (*GetHostnameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostname not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetPort(context.Context, *GetPortRequest) (*GetPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPort not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetServiceName(context.Context, *GetServiceNameRequest) (*GetServiceNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceName not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetServiceType(context.Context, *GetServiceTypeRequest) (*GetServiceTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceType not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) GetSubtypes(context.Context, *GetSubtypesRequest) (*GetSubtypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubtypes not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) RemoveAttribute(context.Context, *RemoveAttributeRequest) (*RemoveAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAttribute not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetAttribute(context.Context, *SetAttributeRequest) (*SetAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAttribute not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetHost(context.Context, *SetHostRequest) (*SetHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHost not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetHostAddresses(context.Context, *SetHostAddressesRequest) (*SetHostAddressesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHostAddresses not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetNetwork(context.Context, *SetNetworkRequest) (*SetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNetwork not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetPort(context.Context, *SetPortRequest) (*SetPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPort not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetServiceName(context.Context, *SetServiceNameRequest) (*SetServiceNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetServiceName not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetServiceType(context.Context, *SetServiceTypeRequest) (*SetServiceTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetServiceType not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) SetSubtypes(context.Context, *SetSubtypesRequest) (*SetSubtypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSubtypes not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) ToString(context.Context, *ToStringRequest) (*ToStringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToString not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) WriteToParcel(context.Context, *WriteToParcelRequest) (*WriteToParcelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteToParcel not implemented")
}
func (UnimplementedNsdServiceInfoServiceServer) mustEmbedUnimplementedNsdServiceInfoServiceServer() {}
func (UnimplementedNsdServiceInfoServiceServer) testEmbeddedByValue()                               {}

// UnsafeNsdServiceInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NsdServiceInfoServiceServer will
// result in compilation errors.
type UnsafeNsdServiceInfoServiceServer interface {
	mustEmbedUnimplementedNsdServiceInfoServiceServer()
}

func RegisterNsdServiceInfoServiceServer(s grpc.ServiceRegistrar, srv NsdServiceInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedNsdServiceInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NsdServiceInfoService_ServiceDesc, srv)
}

func _NsdServiceInfoService_DescribeContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).DescribeContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_DescribeContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).DescribeContents(ctx, req.(*DescribeContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetHostAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetHostAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetHostAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetHostAddresses(ctx, req.(*GetHostAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetHostname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetHostname(ctx, req.(*GetHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetPort(ctx, req.(*GetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetServiceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetServiceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetServiceName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetServiceName(ctx, req.(*GetServiceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetServiceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetServiceType(ctx, req.(*GetServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_GetSubtypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).GetSubtypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_GetSubtypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).GetSubtypes(ctx, req.(*GetSubtypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_RemoveAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).RemoveAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_RemoveAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).RemoveAttribute(ctx, req.(*RemoveAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetAttribute(ctx, req.(*SetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetHost(ctx, req.(*SetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetHostAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHostAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetHostAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetHostAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetHostAddresses(ctx, req.(*SetHostAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetNetwork(ctx, req.(*SetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetPort(ctx, req.(*SetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetServiceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetServiceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetServiceName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetServiceName(ctx, req.(*SetServiceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetServiceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetServiceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetServiceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetServiceType(ctx, req.(*SetServiceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_SetSubtypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSubtypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).SetSubtypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_SetSubtypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).SetSubtypes(ctx, req.(*SetSubtypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_ToString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).ToString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_ToString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).ToString(ctx, req.(*ToStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NsdServiceInfoService_WriteToParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteToParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NsdServiceInfoServiceServer).WriteToParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NsdServiceInfoService_WriteToParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NsdServiceInfoServiceServer).WriteToParcel(ctx, req.(*WriteToParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NsdServiceInfoService_ServiceDesc is the grpc.ServiceDesc for NsdServiceInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NsdServiceInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nsd.NsdServiceInfoService",
	HandlerType: (*NsdServiceInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeContents",
			Handler:    _NsdServiceInfoService_DescribeContents_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _NsdServiceInfoService_GetHost_Handler,
		},
		{
			MethodName: "GetHostAddresses",
			Handler:    _NsdServiceInfoService_GetHostAddresses_Handler,
		},
		{
			MethodName: "GetHostname",
			Handler:    _NsdServiceInfoService_GetHostname_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NsdServiceInfoService_GetNetwork_Handler,
		},
		{
			MethodName: "GetPort",
			Handler:    _NsdServiceInfoService_GetPort_Handler,
		},
		{
			MethodName: "GetServiceName",
			Handler:    _NsdServiceInfoService_GetServiceName_Handler,
		},
		{
			MethodName: "GetServiceType",
			Handler:    _NsdServiceInfoService_GetServiceType_Handler,
		},
		{
			MethodName: "GetSubtypes",
			Handler:    _NsdServiceInfoService_GetSubtypes_Handler,
		},
		{
			MethodName: "RemoveAttribute",
			Handler:    _NsdServiceInfoService_RemoveAttribute_Handler,
		},
		{
			MethodName: "SetAttribute",
			Handler:    _NsdServiceInfoService_SetAttribute_Handler,
		},
		{
			MethodName: "SetHost",
			Handler:    _NsdServiceInfoService_SetHost_Handler,
		},
		{
			MethodName: "SetHostAddresses",
			Handler:    _NsdServiceInfoService_SetHostAddresses_Handler,
		},
		{
			MethodName: "SetNetwork",
			Handler:    _NsdServiceInfoService_SetNetwork_Handler,
		},
		{
			MethodName: "SetPort",
			Handler:    _NsdServiceInfoService_SetPort_Handler,
		},
		{
			MethodName: "SetServiceName",
			Handler:    _NsdServiceInfoService_SetServiceName_Handler,
		},
		{
			MethodName: "SetServiceType",
			Handler:    _NsdServiceInfoService_SetServiceType_Handler,
		},
		{
			MethodName: "SetSubtypes",
			Handler:    _NsdServiceInfoService_SetSubtypes_Handler,
		},
		{
			MethodName: "ToString",
			Handler:    _NsdServiceInfoService_ToString_Handler,
		},
		{
			MethodName: "WriteToParcel",
			Handler:    _NsdServiceInfoService_WriteToParcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nsd/nsd.proto",
}
