// Code generated by protogen. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/audiomanager/audiomanager.proto

package audiomanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_GetDevicesRaw_FullMethodName                 = "/audiomanager.ManagerService/GetDevicesRaw"
	ManagerService_RegisterAudioDeviceCallback_FullMethodName   = "/audiomanager.ManagerService/RegisterAudioDeviceCallback"
	ManagerService_UnregisterAudioDeviceCallback_FullMethodName = "/audiomanager.ManagerService/UnregisterAudioDeviceCallback"
	ManagerService_RequestAudioFocusRaw_FullMethodName          = "/audiomanager.ManagerService/RequestAudioFocusRaw"
	ManagerService_AbandonAudioFocusRequest_FullMethodName      = "/audiomanager.ManagerService/AbandonAudioFocusRequest"
	ManagerService_GetStreamVolume_FullMethodName               = "/audiomanager.ManagerService/GetStreamVolume"
	ManagerService_SetStreamVolume_FullMethodName               = "/audiomanager.ManagerService/SetStreamVolume"
	ManagerService_GetStreamMaxVolume_FullMethodName            = "/audiomanager.ManagerService/GetStreamMaxVolume"
	ManagerService_IsSpeakerphoneOn_FullMethodName              = "/audiomanager.ManagerService/IsSpeakerphoneOn"
	ManagerService_SetSpeakerphoneOn_FullMethodName             = "/audiomanager.ManagerService/SetSpeakerphoneOn"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagerServiceClient interface {
	GetDevicesRaw(ctx context.Context, in *GetDevicesRawRequest, opts ...grpc.CallOption) (*GetDevicesRawResponse, error)
	RegisterAudioDeviceCallback(ctx context.Context, in *RegisterAudioDeviceCallbackRequest, opts ...grpc.CallOption) (*RegisterAudioDeviceCallbackResponse, error)
	UnregisterAudioDeviceCallback(ctx context.Context, in *UnregisterAudioDeviceCallbackRequest, opts ...grpc.CallOption) (*UnregisterAudioDeviceCallbackResponse, error)
	RequestAudioFocusRaw(ctx context.Context, in *RequestAudioFocusRawRequest, opts ...grpc.CallOption) (*RequestAudioFocusRawResponse, error)
	AbandonAudioFocusRequest(ctx context.Context, in *AbandonAudioFocusRequestRequest, opts ...grpc.CallOption) (*AbandonAudioFocusRequestResponse, error)
	GetStreamVolume(ctx context.Context, in *GetStreamVolumeRequest, opts ...grpc.CallOption) (*GetStreamVolumeResponse, error)
	SetStreamVolume(ctx context.Context, in *SetStreamVolumeRequest, opts ...grpc.CallOption) (*SetStreamVolumeResponse, error)
	GetStreamMaxVolume(ctx context.Context, in *GetStreamMaxVolumeRequest, opts ...grpc.CallOption) (*GetStreamMaxVolumeResponse, error)
	IsSpeakerphoneOn(ctx context.Context, in *IsSpeakerphoneOnRequest, opts ...grpc.CallOption) (*IsSpeakerphoneOnResponse, error)
	SetSpeakerphoneOn(ctx context.Context, in *SetSpeakerphoneOnRequest, opts ...grpc.CallOption) (*SetSpeakerphoneOnResponse, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) GetDevicesRaw(ctx context.Context, in *GetDevicesRawRequest, opts ...grpc.CallOption) (*GetDevicesRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesRawResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetDevicesRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RegisterAudioDeviceCallback(ctx context.Context, in *RegisterAudioDeviceCallbackRequest, opts ...grpc.CallOption) (*RegisterAudioDeviceCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAudioDeviceCallbackResponse)
	err := c.cc.Invoke(ctx, ManagerService_RegisterAudioDeviceCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UnregisterAudioDeviceCallback(ctx context.Context, in *UnregisterAudioDeviceCallbackRequest, opts ...grpc.CallOption) (*UnregisterAudioDeviceCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterAudioDeviceCallbackResponse)
	err := c.cc.Invoke(ctx, ManagerService_UnregisterAudioDeviceCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RequestAudioFocusRaw(ctx context.Context, in *RequestAudioFocusRawRequest, opts ...grpc.CallOption) (*RequestAudioFocusRawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAudioFocusRawResponse)
	err := c.cc.Invoke(ctx, ManagerService_RequestAudioFocusRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) AbandonAudioFocusRequest(ctx context.Context, in *AbandonAudioFocusRequestRequest, opts ...grpc.CallOption) (*AbandonAudioFocusRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonAudioFocusRequestResponse)
	err := c.cc.Invoke(ctx, ManagerService_AbandonAudioFocusRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetStreamVolume(ctx context.Context, in *GetStreamVolumeRequest, opts ...grpc.CallOption) (*GetStreamVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamVolumeResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetStreamVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SetStreamVolume(ctx context.Context, in *SetStreamVolumeRequest, opts ...grpc.CallOption) (*SetStreamVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStreamVolumeResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetStreamVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetStreamMaxVolume(ctx context.Context, in *GetStreamMaxVolumeRequest, opts ...grpc.CallOption) (*GetStreamMaxVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamMaxVolumeResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetStreamMaxVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) IsSpeakerphoneOn(ctx context.Context, in *IsSpeakerphoneOnRequest, opts ...grpc.CallOption) (*IsSpeakerphoneOnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsSpeakerphoneOnResponse)
	err := c.cc.Invoke(ctx, ManagerService_IsSpeakerphoneOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SetSpeakerphoneOn(ctx context.Context, in *SetSpeakerphoneOnRequest, opts ...grpc.CallOption) (*SetSpeakerphoneOnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSpeakerphoneOnResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetSpeakerphoneOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
type ManagerServiceServer interface {
	GetDevicesRaw(context.Context, *GetDevicesRawRequest) (*GetDevicesRawResponse, error)
	RegisterAudioDeviceCallback(context.Context, *RegisterAudioDeviceCallbackRequest) (*RegisterAudioDeviceCallbackResponse, error)
	UnregisterAudioDeviceCallback(context.Context, *UnregisterAudioDeviceCallbackRequest) (*UnregisterAudioDeviceCallbackResponse, error)
	RequestAudioFocusRaw(context.Context, *RequestAudioFocusRawRequest) (*RequestAudioFocusRawResponse, error)
	AbandonAudioFocusRequest(context.Context, *AbandonAudioFocusRequestRequest) (*AbandonAudioFocusRequestResponse, error)
	GetStreamVolume(context.Context, *GetStreamVolumeRequest) (*GetStreamVolumeResponse, error)
	SetStreamVolume(context.Context, *SetStreamVolumeRequest) (*SetStreamVolumeResponse, error)
	GetStreamMaxVolume(context.Context, *GetStreamMaxVolumeRequest) (*GetStreamMaxVolumeResponse, error)
	IsSpeakerphoneOn(context.Context, *IsSpeakerphoneOnRequest) (*IsSpeakerphoneOnResponse, error)
	SetSpeakerphoneOn(context.Context, *SetSpeakerphoneOnRequest) (*SetSpeakerphoneOnResponse, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) GetDevicesRaw(context.Context, *GetDevicesRawRequest) (*GetDevicesRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevicesRaw not implemented")
}
func (UnimplementedManagerServiceServer) RegisterAudioDeviceCallback(context.Context, *RegisterAudioDeviceCallbackRequest) (*RegisterAudioDeviceCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAudioDeviceCallback not implemented")
}
func (UnimplementedManagerServiceServer) UnregisterAudioDeviceCallback(context.Context, *UnregisterAudioDeviceCallbackRequest) (*UnregisterAudioDeviceCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterAudioDeviceCallback not implemented")
}
func (UnimplementedManagerServiceServer) RequestAudioFocusRaw(context.Context, *RequestAudioFocusRawRequest) (*RequestAudioFocusRawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAudioFocusRaw not implemented")
}
func (UnimplementedManagerServiceServer) AbandonAudioFocusRequest(context.Context, *AbandonAudioFocusRequestRequest) (*AbandonAudioFocusRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonAudioFocusRequest not implemented")
}
func (UnimplementedManagerServiceServer) GetStreamVolume(context.Context, *GetStreamVolumeRequest) (*GetStreamVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamVolume not implemented")
}
func (UnimplementedManagerServiceServer) SetStreamVolume(context.Context, *SetStreamVolumeRequest) (*SetStreamVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStreamVolume not implemented")
}
func (UnimplementedManagerServiceServer) GetStreamMaxVolume(context.Context, *GetStreamMaxVolumeRequest) (*GetStreamMaxVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamMaxVolume not implemented")
}
func (UnimplementedManagerServiceServer) IsSpeakerphoneOn(context.Context, *IsSpeakerphoneOnRequest) (*IsSpeakerphoneOnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsSpeakerphoneOn not implemented")
}
func (UnimplementedManagerServiceServer) SetSpeakerphoneOn(context.Context, *SetSpeakerphoneOnRequest) (*SetSpeakerphoneOnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSpeakerphoneOn not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_GetDevicesRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetDevicesRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetDevicesRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetDevicesRaw(ctx, req.(*GetDevicesRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RegisterAudioDeviceCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAudioDeviceCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RegisterAudioDeviceCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RegisterAudioDeviceCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RegisterAudioDeviceCallback(ctx, req.(*RegisterAudioDeviceCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UnregisterAudioDeviceCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterAudioDeviceCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).UnregisterAudioDeviceCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_UnregisterAudioDeviceCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).UnregisterAudioDeviceCallback(ctx, req.(*UnregisterAudioDeviceCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RequestAudioFocusRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAudioFocusRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RequestAudioFocusRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RequestAudioFocusRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RequestAudioFocusRaw(ctx, req.(*RequestAudioFocusRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_AbandonAudioFocusRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonAudioFocusRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).AbandonAudioFocusRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_AbandonAudioFocusRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).AbandonAudioFocusRequest(ctx, req.(*AbandonAudioFocusRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetStreamVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetStreamVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetStreamVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetStreamVolume(ctx, req.(*GetStreamVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SetStreamVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStreamVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetStreamVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetStreamVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetStreamVolume(ctx, req.(*SetStreamVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetStreamMaxVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamMaxVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetStreamMaxVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetStreamMaxVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetStreamMaxVolume(ctx, req.(*GetStreamMaxVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_IsSpeakerphoneOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSpeakerphoneOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).IsSpeakerphoneOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_IsSpeakerphoneOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).IsSpeakerphoneOn(ctx, req.(*IsSpeakerphoneOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SetSpeakerphoneOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpeakerphoneOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetSpeakerphoneOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetSpeakerphoneOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetSpeakerphoneOn(ctx, req.(*SetSpeakerphoneOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiomanager.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevicesRaw",
			Handler:    _ManagerService_GetDevicesRaw_Handler,
		},
		{
			MethodName: "RegisterAudioDeviceCallback",
			Handler:    _ManagerService_RegisterAudioDeviceCallback_Handler,
		},
		{
			MethodName: "UnregisterAudioDeviceCallback",
			Handler:    _ManagerService_UnregisterAudioDeviceCallback_Handler,
		},
		{
			MethodName: "RequestAudioFocusRaw",
			Handler:    _ManagerService_RequestAudioFocusRaw_Handler,
		},
		{
			MethodName: "AbandonAudioFocusRequest",
			Handler:    _ManagerService_AbandonAudioFocusRequest_Handler,
		},
		{
			MethodName: "GetStreamVolume",
			Handler:    _ManagerService_GetStreamVolume_Handler,
		},
		{
			MethodName: "SetStreamVolume",
			Handler:    _ManagerService_SetStreamVolume_Handler,
		},
		{
			MethodName: "GetStreamMaxVolume",
			Handler:    _ManagerService_GetStreamMaxVolume_Handler,
		},
		{
			MethodName: "IsSpeakerphoneOn",
			Handler:    _ManagerService_IsSpeakerphoneOn_Handler,
		},
		{
			MethodName: "SetSpeakerphoneOn",
			Handler:    _ManagerService_SetSpeakerphoneOn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/audiomanager/audiomanager.proto",
}

const (
	AudioFocusRequestBuilderService_SetOnAudioFocusChangeListener_FullMethodName = "/audiomanager.AudioFocusRequestBuilderService/SetOnAudioFocusChangeListener"
	AudioFocusRequestBuilderService_Build_FullMethodName                         = "/audiomanager.AudioFocusRequestBuilderService/Build"
)

// AudioFocusRequestBuilderServiceClient is the client API for AudioFocusRequestBuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioFocusRequestBuilderServiceClient interface {
	SetOnAudioFocusChangeListener(ctx context.Context, in *SetOnAudioFocusChangeListenerRequest, opts ...grpc.CallOption) (*SetOnAudioFocusChangeListenerResponse, error)
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type audioFocusRequestBuilderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioFocusRequestBuilderServiceClient(cc grpc.ClientConnInterface) AudioFocusRequestBuilderServiceClient {
	return &audioFocusRequestBuilderServiceClient{cc}
}

func (c *audioFocusRequestBuilderServiceClient) SetOnAudioFocusChangeListener(ctx context.Context, in *SetOnAudioFocusChangeListenerRequest, opts ...grpc.CallOption) (*SetOnAudioFocusChangeListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOnAudioFocusChangeListenerResponse)
	err := c.cc.Invoke(ctx, AudioFocusRequestBuilderService_SetOnAudioFocusChangeListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioFocusRequestBuilderServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, AudioFocusRequestBuilderService_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioFocusRequestBuilderServiceServer is the server API for AudioFocusRequestBuilderService service.
// All implementations must embed UnimplementedAudioFocusRequestBuilderServiceServer
// for forward compatibility.
type AudioFocusRequestBuilderServiceServer interface {
	SetOnAudioFocusChangeListener(context.Context, *SetOnAudioFocusChangeListenerRequest) (*SetOnAudioFocusChangeListenerResponse, error)
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedAudioFocusRequestBuilderServiceServer()
}

// UnimplementedAudioFocusRequestBuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioFocusRequestBuilderServiceServer struct{}

func (UnimplementedAudioFocusRequestBuilderServiceServer) SetOnAudioFocusChangeListener(context.Context, *SetOnAudioFocusChangeListenerRequest) (*SetOnAudioFocusChangeListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOnAudioFocusChangeListener not implemented")
}
func (UnimplementedAudioFocusRequestBuilderServiceServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedAudioFocusRequestBuilderServiceServer) mustEmbedUnimplementedAudioFocusRequestBuilderServiceServer() {
}
func (UnimplementedAudioFocusRequestBuilderServiceServer) testEmbeddedByValue() {}

// UnsafeAudioFocusRequestBuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioFocusRequestBuilderServiceServer will
// result in compilation errors.
type UnsafeAudioFocusRequestBuilderServiceServer interface {
	mustEmbedUnimplementedAudioFocusRequestBuilderServiceServer()
}

func RegisterAudioFocusRequestBuilderServiceServer(s grpc.ServiceRegistrar, srv AudioFocusRequestBuilderServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioFocusRequestBuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioFocusRequestBuilderService_ServiceDesc, srv)
}

func _AudioFocusRequestBuilderService_SetOnAudioFocusChangeListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOnAudioFocusChangeListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioFocusRequestBuilderServiceServer).SetOnAudioFocusChangeListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioFocusRequestBuilderService_SetOnAudioFocusChangeListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioFocusRequestBuilderServiceServer).SetOnAudioFocusChangeListener(ctx, req.(*SetOnAudioFocusChangeListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioFocusRequestBuilderService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioFocusRequestBuilderServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioFocusRequestBuilderService_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioFocusRequestBuilderServiceServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioFocusRequestBuilderService_ServiceDesc is the grpc.ServiceDesc for AudioFocusRequestBuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioFocusRequestBuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiomanager.AudioFocusRequestBuilderService",
	HandlerType: (*AudioFocusRequestBuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetOnAudioFocusChangeListener",
			Handler:    _AudioFocusRequestBuilderService_SetOnAudioFocusChangeListener_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _AudioFocusRequestBuilderService_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/audiomanager/audiomanager.proto",
}

const (
	AudioDeviceCallbackService_SubscribeAudioDeviceCallback_FullMethodName = "/audiomanager.AudioDeviceCallbackService/SubscribeAudioDeviceCallback"
)

// AudioDeviceCallbackServiceClient is the client API for AudioDeviceCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioDeviceCallbackServiceClient interface {
	// Server-streaming events from android.media.AudioDeviceCallback
	SubscribeAudioDeviceCallback(ctx context.Context, in *SubscribeAudioDeviceCallbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioDeviceCallbackEvent], error)
}

type audioDeviceCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioDeviceCallbackServiceClient(cc grpc.ClientConnInterface) AudioDeviceCallbackServiceClient {
	return &audioDeviceCallbackServiceClient{cc}
}

func (c *audioDeviceCallbackServiceClient) SubscribeAudioDeviceCallback(ctx context.Context, in *SubscribeAudioDeviceCallbackRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioDeviceCallbackEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioDeviceCallbackService_ServiceDesc.Streams[0], AudioDeviceCallbackService_SubscribeAudioDeviceCallback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAudioDeviceCallbackRequest, AudioDeviceCallbackEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioDeviceCallbackService_SubscribeAudioDeviceCallbackClient = grpc.ServerStreamingClient[AudioDeviceCallbackEvent]

// AudioDeviceCallbackServiceServer is the server API for AudioDeviceCallbackService service.
// All implementations must embed UnimplementedAudioDeviceCallbackServiceServer
// for forward compatibility.
type AudioDeviceCallbackServiceServer interface {
	// Server-streaming events from android.media.AudioDeviceCallback
	SubscribeAudioDeviceCallback(*SubscribeAudioDeviceCallbackRequest, grpc.ServerStreamingServer[AudioDeviceCallbackEvent]) error
	mustEmbedUnimplementedAudioDeviceCallbackServiceServer()
}

// UnimplementedAudioDeviceCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioDeviceCallbackServiceServer struct{}

func (UnimplementedAudioDeviceCallbackServiceServer) SubscribeAudioDeviceCallback(*SubscribeAudioDeviceCallbackRequest, grpc.ServerStreamingServer[AudioDeviceCallbackEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAudioDeviceCallback not implemented")
}
func (UnimplementedAudioDeviceCallbackServiceServer) mustEmbedUnimplementedAudioDeviceCallbackServiceServer() {
}
func (UnimplementedAudioDeviceCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeAudioDeviceCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioDeviceCallbackServiceServer will
// result in compilation errors.
type UnsafeAudioDeviceCallbackServiceServer interface {
	mustEmbedUnimplementedAudioDeviceCallbackServiceServer()
}

func RegisterAudioDeviceCallbackServiceServer(s grpc.ServiceRegistrar, srv AudioDeviceCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioDeviceCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioDeviceCallbackService_ServiceDesc, srv)
}

func _AudioDeviceCallbackService_SubscribeAudioDeviceCallback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAudioDeviceCallbackRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioDeviceCallbackServiceServer).SubscribeAudioDeviceCallback(m, &grpc.GenericServerStream[SubscribeAudioDeviceCallbackRequest, AudioDeviceCallbackEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioDeviceCallbackService_SubscribeAudioDeviceCallbackServer = grpc.ServerStreamingServer[AudioDeviceCallbackEvent]

// AudioDeviceCallbackService_ServiceDesc is the grpc.ServiceDesc for AudioDeviceCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioDeviceCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiomanager.AudioDeviceCallbackService",
	HandlerType: (*AudioDeviceCallbackServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAudioDeviceCallback",
			Handler:       _AudioDeviceCallbackService_SubscribeAudioDeviceCallback_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/audiomanager/audiomanager.proto",
}

const (
	AudioFocusChangeListenerService_SubscribeAudioFocusChangeListener_FullMethodName = "/audiomanager.AudioFocusChangeListenerService/SubscribeAudioFocusChangeListener"
)

// AudioFocusChangeListenerServiceClient is the client API for AudioFocusChangeListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioFocusChangeListenerServiceClient interface {
	// Server-streaming events from android.media.AudioManager$OnAudioFocusChangeListener
	SubscribeAudioFocusChangeListener(ctx context.Context, in *SubscribeAudioFocusChangeListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioFocusChangeListenerEvent], error)
}

type audioFocusChangeListenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioFocusChangeListenerServiceClient(cc grpc.ClientConnInterface) AudioFocusChangeListenerServiceClient {
	return &audioFocusChangeListenerServiceClient{cc}
}

func (c *audioFocusChangeListenerServiceClient) SubscribeAudioFocusChangeListener(ctx context.Context, in *SubscribeAudioFocusChangeListenerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioFocusChangeListenerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioFocusChangeListenerService_ServiceDesc.Streams[0], AudioFocusChangeListenerService_SubscribeAudioFocusChangeListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAudioFocusChangeListenerRequest, AudioFocusChangeListenerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioFocusChangeListenerService_SubscribeAudioFocusChangeListenerClient = grpc.ServerStreamingClient[AudioFocusChangeListenerEvent]

// AudioFocusChangeListenerServiceServer is the server API for AudioFocusChangeListenerService service.
// All implementations must embed UnimplementedAudioFocusChangeListenerServiceServer
// for forward compatibility.
type AudioFocusChangeListenerServiceServer interface {
	// Server-streaming events from android.media.AudioManager$OnAudioFocusChangeListener
	SubscribeAudioFocusChangeListener(*SubscribeAudioFocusChangeListenerRequest, grpc.ServerStreamingServer[AudioFocusChangeListenerEvent]) error
	mustEmbedUnimplementedAudioFocusChangeListenerServiceServer()
}

// UnimplementedAudioFocusChangeListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioFocusChangeListenerServiceServer struct{}

func (UnimplementedAudioFocusChangeListenerServiceServer) SubscribeAudioFocusChangeListener(*SubscribeAudioFocusChangeListenerRequest, grpc.ServerStreamingServer[AudioFocusChangeListenerEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAudioFocusChangeListener not implemented")
}
func (UnimplementedAudioFocusChangeListenerServiceServer) mustEmbedUnimplementedAudioFocusChangeListenerServiceServer() {
}
func (UnimplementedAudioFocusChangeListenerServiceServer) testEmbeddedByValue() {}

// UnsafeAudioFocusChangeListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioFocusChangeListenerServiceServer will
// result in compilation errors.
type UnsafeAudioFocusChangeListenerServiceServer interface {
	mustEmbedUnimplementedAudioFocusChangeListenerServiceServer()
}

func RegisterAudioFocusChangeListenerServiceServer(s grpc.ServiceRegistrar, srv AudioFocusChangeListenerServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioFocusChangeListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioFocusChangeListenerService_ServiceDesc, srv)
}

func _AudioFocusChangeListenerService_SubscribeAudioFocusChangeListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAudioFocusChangeListenerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioFocusChangeListenerServiceServer).SubscribeAudioFocusChangeListener(m, &grpc.GenericServerStream[SubscribeAudioFocusChangeListenerRequest, AudioFocusChangeListenerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioFocusChangeListenerService_SubscribeAudioFocusChangeListenerServer = grpc.ServerStreamingServer[AudioFocusChangeListenerEvent]

// AudioFocusChangeListenerService_ServiceDesc is the grpc.ServiceDesc for AudioFocusChangeListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioFocusChangeListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiomanager.AudioFocusChangeListenerService",
	HandlerType: (*AudioFocusChangeListenerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAudioFocusChangeListener",
			Handler:       _AudioFocusChangeListenerService_SubscribeAudioFocusChangeListener_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/audiomanager/audiomanager.proto",
}
