// Code generated by javagen. DO NOT EDIT.

package shapes

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// RectShape wraps android.graphics.drawable.shapes.RectShape.
type RectShape struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// NewRectShape creates a new android.graphics.drawable.shapes.RectShape instance.
func NewRectShape(vm *jni.VM) (*RectShape, error) {
	var t RectShape
	t.VM = vm

	err := vm.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		obj, err := env.NewObject((*jni.Class)(unsafe.Pointer(clsRectShape)), midRectShapeCtor)
		if err != nil {
			return err
		}
		t.Obj = env.NewGlobalRef(obj)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Clone0 calls android.graphics.drawable.shapes.RectShape.clone.
func (m *RectShape) Clone0() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeClone0 == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.clone is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midRectShapeClone0,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Draw calls android.graphics.drawable.shapes.RectShape.draw.
func (m *RectShape) Draw(arg0 *jni.Object, arg1 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeDraw == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.draw is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectShapeDraw, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		return callErr
	})
	return callErr
}

// Equals calls android.graphics.drawable.shapes.RectShape.equals.
func (m *RectShape) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeEquals == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midRectShapeEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetOutline calls android.graphics.drawable.shapes.RectShape.getOutline.
func (m *RectShape) GetOutline(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeGetOutline == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.getOutline is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midRectShapeGetOutline, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// HashCode calls android.graphics.drawable.shapes.RectShape.hashCode.
func (m *RectShape) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeHashCode == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midRectShapeHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// Clone0_1 calls android.graphics.drawable.shapes.RectShape.clone.
func (m *RectShape) Clone0_1() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeClone0_1 == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.clone is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midRectShapeClone0_1,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Clone0_2 calls android.graphics.drawable.shapes.RectShape.clone.
func (m *RectShape) Clone0_2() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midRectShapeClone0_2 == nil {
			callErr = fmt.Errorf("android.graphics.drawable.shapes.RectShape.clone is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midRectShapeClone0_2,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}
