// Code generated by javagen. DO NOT EDIT.

package text

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Selection wraps android.text.Selection.
type Selection struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// ToString calls android.text.Selection.toString.
func (m *Selection) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionToString == nil {
			callErr = fmt.Errorf("android.text.Selection.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midSelectionToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// ExtendDown calls android.text.Selection.extendDown.
func (m *Selection) ExtendDown(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendDown == nil {
			callErr = fmt.Errorf("android.text.Selection.extendDown is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendDown, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendLeft calls android.text.Selection.extendLeft.
func (m *Selection) ExtendLeft(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendLeft == nil {
			callErr = fmt.Errorf("android.text.Selection.extendLeft is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendLeft, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendRight calls android.text.Selection.extendRight.
func (m *Selection) ExtendRight(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendRight == nil {
			callErr = fmt.Errorf("android.text.Selection.extendRight is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendRight, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendSelection calls android.text.Selection.extendSelection.
func (m *Selection) ExtendSelection(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendSelection == nil {
			callErr = fmt.Errorf("android.text.Selection.extendSelection is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendSelection, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// ExtendToLeftEdge calls android.text.Selection.extendToLeftEdge.
func (m *Selection) ExtendToLeftEdge(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendToLeftEdge == nil {
			callErr = fmt.Errorf("android.text.Selection.extendToLeftEdge is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendToLeftEdge, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendToParagraphEnd calls android.text.Selection.extendToParagraphEnd.
func (m *Selection) ExtendToParagraphEnd(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendToParagraphEnd == nil {
			callErr = fmt.Errorf("android.text.Selection.extendToParagraphEnd is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendToParagraphEnd, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendToParagraphStart calls android.text.Selection.extendToParagraphStart.
func (m *Selection) ExtendToParagraphStart(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendToParagraphStart == nil {
			callErr = fmt.Errorf("android.text.Selection.extendToParagraphStart is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendToParagraphStart, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendToRightEdge calls android.text.Selection.extendToRightEdge.
func (m *Selection) ExtendToRightEdge(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendToRightEdge == nil {
			callErr = fmt.Errorf("android.text.Selection.extendToRightEdge is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendToRightEdge, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ExtendUp calls android.text.Selection.extendUp.
func (m *Selection) ExtendUp(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionExtendUp == nil {
			callErr = fmt.Errorf("android.text.Selection.extendUp is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionExtendUp, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetSelectionEnd calls android.text.Selection.getSelectionEnd.
func (m *Selection) GetSelectionEnd(arg0 string) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionGetSelectionEnd == nil {
			callErr = fmt.Errorf("android.text.Selection.getSelectionEnd is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionGetSelectionEnd, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetSelectionStart calls android.text.Selection.getSelectionStart.
func (m *Selection) GetSelectionStart(arg0 string) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionGetSelectionStart == nil {
			callErr = fmt.Errorf("android.text.Selection.getSelectionStart is not available on this device")
			return callErr
		}
		jArg0, err := env.NewStringUTF(arg0)
		if err != nil {
			return err
		}
		defer env.DeleteLocalRef(&jArg0.Object)

		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionGetSelectionStart, jni.ObjectValue(&jArg0.Object),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// MoveDown calls android.text.Selection.moveDown.
func (m *Selection) MoveDown(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveDown == nil {
			callErr = fmt.Errorf("android.text.Selection.moveDown is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveDown, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveLeft calls android.text.Selection.moveLeft.
func (m *Selection) MoveLeft(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveLeft == nil {
			callErr = fmt.Errorf("android.text.Selection.moveLeft is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveLeft, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveRight calls android.text.Selection.moveRight.
func (m *Selection) MoveRight(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveRight == nil {
			callErr = fmt.Errorf("android.text.Selection.moveRight is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveRight, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveToLeftEdge calls android.text.Selection.moveToLeftEdge.
func (m *Selection) MoveToLeftEdge(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveToLeftEdge == nil {
			callErr = fmt.Errorf("android.text.Selection.moveToLeftEdge is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveToLeftEdge, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveToParagraphEnd calls android.text.Selection.moveToParagraphEnd.
func (m *Selection) MoveToParagraphEnd(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveToParagraphEnd == nil {
			callErr = fmt.Errorf("android.text.Selection.moveToParagraphEnd is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveToParagraphEnd, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveToParagraphStart calls android.text.Selection.moveToParagraphStart.
func (m *Selection) MoveToParagraphStart(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveToParagraphStart == nil {
			callErr = fmt.Errorf("android.text.Selection.moveToParagraphStart is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveToParagraphStart, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveToRightEdge calls android.text.Selection.moveToRightEdge.
func (m *Selection) MoveToRightEdge(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveToRightEdge == nil {
			callErr = fmt.Errorf("android.text.Selection.moveToRightEdge is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveToRightEdge, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// MoveUp calls android.text.Selection.moveUp.
func (m *Selection) MoveUp(arg0 *jni.Object, arg1 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionMoveUp == nil {
			callErr = fmt.Errorf("android.text.Selection.moveUp is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallStaticBooleanMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionMoveUp, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// RemoveSelection calls android.text.Selection.removeSelection.
func (m *Selection) RemoveSelection(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionRemoveSelection == nil {
			callErr = fmt.Errorf("android.text.Selection.removeSelection is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionRemoveSelection, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SelectAll calls android.text.Selection.selectAll.
func (m *Selection) SelectAll(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionSelectAll == nil {
			callErr = fmt.Errorf("android.text.Selection.selectAll is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionSelectAll, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// SetSelection2 calls android.text.Selection.setSelection.
func (m *Selection) SetSelection2(arg0 *jni.Object, arg1 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionSetSelection2 == nil {
			callErr = fmt.Errorf("android.text.Selection.setSelection is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionSetSelection2, jni.ObjectValue(arg0), jni.IntValue(arg1),
		)
		return callErr
	})
	return callErr
}

// SetSelection3_1 calls android.text.Selection.setSelection.
func (m *Selection) SetSelection3_1(
	arg0 *jni.Object,
	arg1 int32,
	arg2 int32,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midSelectionSetSelection3_1 == nil {
			callErr = fmt.Errorf("android.text.Selection.setSelection is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsSelection)),
			midSelectionSetSelection3_1, jni.ObjectValue(arg0), jni.IntValue(arg1), jni.IntValue(arg2),
		)
		return callErr
	})
	return callErr
}
