// Code generated by javagen. DO NOT EDIT.

package location

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// GnssStatusCallback wraps android.location.GnssStatus$Callback.
type GnssStatusCallback struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnFirstFix calls android.location.GnssStatus$Callback.onFirstFix.
func (m *GnssStatusCallback) OnFirstFix(arg0 int32) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midGnssStatusCallbackOnFirstFix == nil {
			callErr = fmt.Errorf("android.location.GnssStatus$Callback.onFirstFix is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midGnssStatusCallbackOnFirstFix, jni.IntValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnSatelliteStatusChanged calls android.location.GnssStatus$Callback.onSatelliteStatusChanged.
func (m *GnssStatusCallback) OnSatelliteStatusChanged(arg0 *jni.Object) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midGnssStatusCallbackOnSatelliteStatusChanged == nil {
			callErr = fmt.Errorf("android.location.GnssStatus$Callback.onSatelliteStatusChanged is not available on this device")
			return callErr
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midGnssStatusCallbackOnSatelliteStatusChanged, jni.ObjectValue(arg0),
		)
		return callErr
	})
	return callErr
}

// OnStarted calls android.location.GnssStatus$Callback.onStarted.
func (m *GnssStatusCallback) OnStarted() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midGnssStatusCallbackOnStarted == nil {
			callErr = fmt.Errorf("android.location.GnssStatus$Callback.onStarted is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midGnssStatusCallbackOnStarted,
		)
		return callErr
	})
	return callErr
}

// OnStopped calls android.location.GnssStatus$Callback.onStopped.
func (m *GnssStatusCallback) OnStopped() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midGnssStatusCallbackOnStopped == nil {
			callErr = fmt.Errorf("android.location.GnssStatus$Callback.onStopped is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midGnssStatusCallbackOnStopped,
		)
		return callErr
	})
	return callErr
}

// ToString calls android.location.GnssStatus$Callback.toString.
func (m *GnssStatusCallback) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midGnssStatusCallbackToString == nil {
			callErr = fmt.Errorf("android.location.GnssStatus$Callback.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midGnssStatusCallbackToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
