// Code generated by javagen. DO NOT EDIT.

package session

import (
	"fmt"
	"unsafe"

	"github.com/xaionaro-go/jni"
	"github.com/xaionaro-go/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Manager wraps android.media.session.MediaSessionManager.
type Manager struct {
	VM  *jni.VM
	Ctx *app.Context
	Obj *jni.GlobalRef
}

// NewManager obtains android.media.session.MediaSessionManager from the Android system service manager.
func NewManager(ctx *app.Context) (*Manager, error) {
	if ctx == nil {
		return nil, fmt.Errorf("Manager: nil Context")
	}
	var mgr Manager
	mgr.VM = ctx.VM
	mgr.Ctx = ctx

	err := mgr.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			return err
		}
		svc, err := ctx.GetSystemService("media_session")
		if err != nil {
			return err
		}
		if svc == nil || svc.Ref() == 0 {
			return fmt.Errorf("media_session service not available")
		}
		mgr.Obj = env.NewGlobalRef(svc)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &mgr, nil
}

// Close releases the global reference to the underlying Java object.
// After Close, the Manager must not be used.
func (m *Manager) Close() {
	if m.Obj != nil {
		m.VM.Do(func(env *jni.Env) error {
			env.DeleteGlobalRef(m.Obj)
			m.Obj = nil
			return nil
		})
	}
}

// getActiveSessionsRaw calls android.media.session.MediaSessionManager.getActiveSessions.
func (m *Manager) getActiveSessionsRaw(notificationListener *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}

		result, callErr = env.CallObjectMethod(
			m.Obj,
			midManagergetActiveSessionsRaw, jni.ObjectValue(notificationListener),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// addOnActiveSessionsChangedListener calls android.media.session.MediaSessionManager.addOnActiveSessionsChangedListener.
func (m *Manager) addOnActiveSessionsChangedListener(listener *jni.Object, notificationListener *jni.Object) error {

	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midManageraddOnActiveSessionsChangedListener, jni.ObjectValue(listener), jni.ObjectValue(notificationListener),
		)
		return callErr
	})
	return callErr
}

// removeOnActiveSessionsChangedListener calls android.media.session.MediaSessionManager.removeOnActiveSessionsChangedListener.
func (m *Manager) removeOnActiveSessionsChangedListener(listener *jni.Object) error {

	var callErr error
	m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midManagerremoveOnActiveSessionsChangedListener, jni.ObjectValue(listener),
		)
		return callErr
	})
	return callErr
}
