// Code generated by javagen. DO NOT EDIT.

package view

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// TreeObserverOnWindowFocusChangeListener wraps android.view.ViewTreeObserver$OnWindowFocusChangeListener.
type TreeObserverOnWindowFocusChangeListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnWindowFocusChanged calls android.view.ViewTreeObserver$OnWindowFocusChangeListener.onWindowFocusChanged.
func (m *TreeObserverOnWindowFocusChangeListener) OnWindowFocusChanged(arg0 bool) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTreeObserverOnWindowFocusChangeListenerOnWindowFocusChanged == nil {
			callErr = fmt.Errorf("android.view.ViewTreeObserver$OnWindowFocusChangeListener.onWindowFocusChanged is not available on this device")
			return callErr
		}
		var jArg0 uint8
		if arg0 {
			jArg0 = jniTrue
		}

		callErr = env.CallVoidMethod(
			m.Obj,
			midTreeObserverOnWindowFocusChangeListenerOnWindowFocusChanged, jni.BooleanValue(jArg0),
		)
		return callErr
	})
	return callErr
}
