// Code generated by javagen. DO NOT EDIT.

package view

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// TreeObserverOnDrawListener wraps android.view.ViewTreeObserver$OnDrawListener.
type TreeObserverOnDrawListener struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// OnDraw calls android.view.ViewTreeObserver$OnDrawListener.onDraw.
func (m *TreeObserverOnDrawListener) OnDraw() error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTreeObserverOnDrawListenerOnDraw == nil {
			callErr = fmt.Errorf("android.view.ViewTreeObserver$OnDrawListener.onDraw is not available on this device")
			return callErr
		}
		callErr = env.CallVoidMethod(
			m.Obj,
			midTreeObserverOnDrawListenerOnDraw,
		)
		return callErr
	})
	return callErr
}

// ToString calls android.view.ViewTreeObserver$OnDrawListener.toString.
func (m *TreeObserverOnDrawListener) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midTreeObserverOnDrawListenerToString == nil {
			callErr = fmt.Errorf("android.view.ViewTreeObserver$OnDrawListener.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midTreeObserverOnDrawListenerToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
