// Code generated by javagen. DO NOT EDIT.

package net

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Ikev2VpnProfile wraps android.net.Ikev2VpnProfile.
type Ikev2VpnProfile struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Equals calls android.net.Ikev2VpnProfile.equals.
func (m *Ikev2VpnProfile) Equals(arg0 *jni.Object) (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileEquals == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.equals is not available on this device")
			return callErr
		}

		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midIkev2VpnProfileEquals, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// GetAllowedAlgorithms calls android.net.Ikev2VpnProfile.getAllowedAlgorithms.
func (m *Ikev2VpnProfile) GetAllowedAlgorithms() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetAllowedAlgorithms == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getAllowedAlgorithms is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetAllowedAlgorithms,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetIkeTunnelConnectionParams calls android.net.Ikev2VpnProfile.getIkeTunnelConnectionParams.
func (m *Ikev2VpnProfile) GetIkeTunnelConnectionParams() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetIkeTunnelConnectionParams == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getIkeTunnelConnectionParams is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetIkeTunnelConnectionParams,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetMaxMtu calls android.net.Ikev2VpnProfile.getMaxMtu.
func (m *Ikev2VpnProfile) GetMaxMtu() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetMaxMtu == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getMaxMtu is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midIkev2VpnProfileGetMaxMtu,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetPassword calls android.net.Ikev2VpnProfile.getPassword.
func (m *Ikev2VpnProfile) GetPassword() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetPassword == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getPassword is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetPassword,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetPresharedKey calls android.net.Ikev2VpnProfile.getPresharedKey.
func (m *Ikev2VpnProfile) GetPresharedKey() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetPresharedKey == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getPresharedKey is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetPresharedKey,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetProxyInfo calls android.net.Ikev2VpnProfile.getProxyInfo.
func (m *Ikev2VpnProfile) GetProxyInfo() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetProxyInfo == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getProxyInfo is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetProxyInfo,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetRsaPrivateKey calls android.net.Ikev2VpnProfile.getRsaPrivateKey.
func (m *Ikev2VpnProfile) GetRsaPrivateKey() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetRsaPrivateKey == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getRsaPrivateKey is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetRsaPrivateKey,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetServerAddr calls android.net.Ikev2VpnProfile.getServerAddr.
func (m *Ikev2VpnProfile) GetServerAddr() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetServerAddr == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getServerAddr is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetServerAddr,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetServerRootCaCert calls android.net.Ikev2VpnProfile.getServerRootCaCert.
func (m *Ikev2VpnProfile) GetServerRootCaCert() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetServerRootCaCert == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getServerRootCaCert is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetServerRootCaCert,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetUserCert calls android.net.Ikev2VpnProfile.getUserCert.
func (m *Ikev2VpnProfile) GetUserCert() (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetUserCert == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getUserCert is not available on this device")
			return callErr
		}
		result, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetUserCert,
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// GetUserIdentity calls android.net.Ikev2VpnProfile.getUserIdentity.
func (m *Ikev2VpnProfile) GetUserIdentity() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetUserIdentity == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getUserIdentity is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetUserIdentity,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetUsername calls android.net.Ikev2VpnProfile.getUsername.
func (m *Ikev2VpnProfile) GetUsername() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileGetUsername == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.getUsername is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileGetUsername,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// HashCode calls android.net.Ikev2VpnProfile.hashCode.
func (m *Ikev2VpnProfile) HashCode() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileHashCode == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.hashCode is not available on this device")
			return callErr
		}
		result, callErr = env.CallIntMethod(
			m.Obj,
			midIkev2VpnProfileHashCode,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// IsAutomaticIpVersionSelectionEnabled calls android.net.Ikev2VpnProfile.isAutomaticIpVersionSelectionEnabled.
func (m *Ikev2VpnProfile) IsAutomaticIpVersionSelectionEnabled() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileIsAutomaticIpVersionSelectionEnabled == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.isAutomaticIpVersionSelectionEnabled is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midIkev2VpnProfileIsAutomaticIpVersionSelectionEnabled,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsAutomaticNattKeepaliveTimerEnabled calls android.net.Ikev2VpnProfile.isAutomaticNattKeepaliveTimerEnabled.
func (m *Ikev2VpnProfile) IsAutomaticNattKeepaliveTimerEnabled() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileIsAutomaticNattKeepaliveTimerEnabled == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.isAutomaticNattKeepaliveTimerEnabled is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midIkev2VpnProfileIsAutomaticNattKeepaliveTimerEnabled,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsBypassable calls android.net.Ikev2VpnProfile.isBypassable.
func (m *Ikev2VpnProfile) IsBypassable() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileIsBypassable == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.isBypassable is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midIkev2VpnProfileIsBypassable,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// IsMetered calls android.net.Ikev2VpnProfile.isMetered.
func (m *Ikev2VpnProfile) IsMetered() (bool, error) {
	var result bool
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileIsMetered == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.isMetered is not available on this device")
			return callErr
		}
		var resultRaw uint8
		resultRaw, callErr = env.CallBooleanMethod(
			m.Obj,
			midIkev2VpnProfileIsMetered,
		)
		if callErr != nil {
			return callErr
		}
		result = resultRaw != 0
		return callErr
	})
	return result, callErr
}

// ToString calls android.net.Ikev2VpnProfile.toString.
func (m *Ikev2VpnProfile) ToString() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midIkev2VpnProfileToString == nil {
			callErr = fmt.Errorf("android.net.Ikev2VpnProfile.toString is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallObjectMethod(
			m.Obj,
			midIkev2VpnProfileToString,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}
