// Code generated by javagen. DO NOT EDIT.

package net

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// Proxy wraps android.net.Proxy.
type Proxy struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// GetDefaultHost calls android.net.Proxy.getDefaultHost.
func (m *Proxy) GetDefaultHost() (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProxyGetDefaultHost == nil {
			callErr = fmt.Errorf("android.net.Proxy.getDefaultHost is not available on this device")
			return callErr
		}
		var resultObj *jni.Object
		resultObj, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsProxy)),
			midProxyGetDefaultHost,
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetDefaultPort calls android.net.Proxy.getDefaultPort.
func (m *Proxy) GetDefaultPort() (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProxyGetDefaultPort == nil {
			callErr = fmt.Errorf("android.net.Proxy.getDefaultPort is not available on this device")
			return callErr
		}
		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsProxy)),
			midProxyGetDefaultPort,
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}

// GetHost calls android.net.Proxy.getHost.
func (m *Proxy) GetHost(arg0 *jni.Object) (string, error) {
	var result string
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProxyGetHost == nil {
			callErr = fmt.Errorf("android.net.Proxy.getHost is not available on this device")
			return callErr
		}

		var resultObj *jni.Object
		resultObj, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsProxy)),
			midProxyGetHost, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		result = env.GoString((*jni.String)(unsafe.Pointer(resultObj)))
		return callErr
	})
	return result, callErr
}

// GetPort calls android.net.Proxy.getPort.
func (m *Proxy) GetPort(arg0 *jni.Object) (int32, error) {
	var result int32
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midProxyGetPort == nil {
			callErr = fmt.Errorf("android.net.Proxy.getPort is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticIntMethod(
			(*jni.Class)(unsafe.Pointer(clsProxy)),
			midProxyGetPort, jni.ObjectValue(arg0),
		)
		if callErr != nil {
			return callErr
		}
		return callErr
	})
	return result, callErr
}
