// Code generated by javagen. DO NOT EDIT.

package contacts

import (
	"fmt"
	"unsafe"

	"github.com/AndroidGoLab/jni"
	"github.com/AndroidGoLab/jni/app"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = unsafe.Pointer(nil)
	_ *app.Context
)

// ContractProfileSyncState wraps android.provider.ContactsContract$ProfileSyncState.
type ContractProfileSyncState struct {
	VM  *jni.VM
	Obj *jni.GlobalRef
}

// Get calls android.provider.ContactsContract$ProfileSyncState.get.
func (m *ContractProfileSyncState) Get(arg0 *jni.Object, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContractProfileSyncStateGet == nil {
			callErr = fmt.Errorf("android.provider.ContactsContract$ProfileSyncState.get is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsContractProfileSyncState)),
			midContractProfileSyncStateGet, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// NewSetOperation calls android.provider.ContactsContract$ProfileSyncState.newSetOperation.
func (m *ContractProfileSyncState) NewSetOperation(arg0 *jni.Object, arg1 *jni.Object) (*jni.Object, error) {
	var result *jni.Object
	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContractProfileSyncStateNewSetOperation == nil {
			callErr = fmt.Errorf("android.provider.ContactsContract$ProfileSyncState.newSetOperation is not available on this device")
			return callErr
		}

		result, callErr = env.CallStaticObjectMethod(
			(*jni.Class)(unsafe.Pointer(clsContractProfileSyncState)),
			midContractProfileSyncStateNewSetOperation, jni.ObjectValue(arg0), jni.ObjectValue(arg1),
		)
		if callErr != nil {
			return callErr
		}
		// Convert the JNI local reference to a global reference so the
		// returned object remains valid outside this vm.Do scope.
		if result != nil {
			localRef := result
			result = env.NewGlobalRef(localRef)
			env.DeleteLocalRef(localRef)
		}
		return callErr
	})
	return result, callErr
}

// Set calls android.provider.ContactsContract$ProfileSyncState.set.
func (m *ContractProfileSyncState) Set(
	arg0 *jni.Object,
	arg1 *jni.Object,
	arg2 *jni.Object,
) error {

	var callErr error
	callErr = m.VM.Do(func(env *jni.Env) error {
		if err := ensureInit(env); err != nil {
			callErr = err
			return err
		}
		if midContractProfileSyncStateSet == nil {
			callErr = fmt.Errorf("android.provider.ContactsContract$ProfileSyncState.set is not available on this device")
			return callErr
		}

		callErr = env.CallStaticVoidMethod(
			(*jni.Class)(unsafe.Pointer(clsContractProfileSyncState)),
			midContractProfileSyncStateSet, jni.ObjectValue(arg0), jni.ObjectValue(arg1), jni.ObjectValue(arg2),
		)
		return callErr
	})
	return callErr
}
